/* eslint-disable */
// Generated list of Algerian Communes grouped by EXACT Wilaya name used in the app
export interface CommuneInfo {
  id: number;
  name: string;      // Arabic
  nameAscii: string; // French/ASCII
}

export const ALGERIAN_COMMUNES: Record<string, CommuneInfo[]> = {
  "Adrar": [
    { id: 101, name: "أدرار", nameAscii: "Adrar" },
    { id: 119, name: "اقبلي", nameAscii: "Akabli" },
    { id: 112, name: "أولف", nameAscii: "Aoulef" },
    { id: 122, name: "بودة", nameAscii: "Bouda" },
    { id: 115, name: "فنوغيل", nameAscii: "Fenoughil" },
    { id: 105, name: "إن زغمير", nameAscii: "In Zghmir" },
    { id: 121, name: "أولاد أحمد تيمي", nameAscii: "Ouled Ahmed Timmi" },
    { id: 104, name: "رقان", nameAscii: "Reggane" },
    { id: 118, name: "سالي", nameAscii: "Sali" },
    { id: 126, name: "السبع", nameAscii: "Sebaa" },
    { id: 114, name: "تامنطيط", nameAscii: "Tamantit" },
    { id: 102, name: "تامست", nameAscii: "Tamest" },
    { id: 113, name: "تيمقتن", nameAscii: "Timekten" },
    { id: 106, name: "تيت", nameAscii: "Tit" },
    { id: 108, name: "تسابيت", nameAscii: "Tsabit" },
    { id: 111, name: "زاوية كنتة", nameAscii: "Zaouiet Kounta" },
  ],
  "Chlef": [
    { id: 222, name: "أبو الحسن", nameAscii: "Abou El Hassane" },
    { id: 232, name: "عين مران", nameAscii: "Ain Merane" },
    { id: 203, name: "بنايرية", nameAscii: "Benairia" },
    { id: 235, name: "بني بوعتاب", nameAscii: "Beni Bouattab" },
    { id: 207, name: "بني حواء", nameAscii: "Beni Haoua" },
    { id: 213, name: "بني راشد", nameAscii: "Beni Rached" },
    { id: 212, name: "بوقادير", nameAscii: "Boukadir" },
    { id: 231, name: "بوزغاية", nameAscii: "Bouzeghaia" },
    { id: 234, name: "بريرة", nameAscii: "Breira" },
    { id: 224, name: "الشطية", nameAscii: "Chettia" },
    { id: 201, name: "الشلف", nameAscii: "Chlef" },
    { id: 217, name: "الظهرة", nameAscii: "Dahra" },
    { id: 227, name: "الحجاج", nameAscii: "El Hadjadj" },
    { id: 204, name: "الكريمية", nameAscii: "El Karimia" },
    { id: 223, name: "المرسى", nameAscii: "El Marsa" },
    { id: 209, name: "حرشون", nameAscii: "Harchoun" },
    { id: 215, name: "الهرانفة", nameAscii: "Herenfa" },
    { id: 228, name: "الأبيض مجاجة", nameAscii: "Labiod Medjadja" },
    { id: 226, name: "مصدق", nameAscii: "Moussadek" },
    { id: 229, name: "وادي الفضة", nameAscii: "Oued Fodda" },
    { id: 216, name: "وادي قوسين", nameAscii: "Oued Goussine" },
    { id: 221, name: "وادي سلي", nameAscii: "Oued Sly" },
    { id: 218, name: "أولاد عباس", nameAscii: "Ouled Abbes" },
    { id: 230, name: "أولاد بن عبد القادر", nameAscii: "Ouled Ben Abdelkader" },
    { id: 210, name: "أولاد فارس", nameAscii: "Ouled Fares" },
    { id: 233, name: "أم الدروع", nameAscii: "Oum Drou" },
    { id: 219, name: "سنجاس", nameAscii: "Sendjas" },
    { id: 225, name: "سيدي عبد الرحمن", nameAscii: "Sidi Abderrahmane" },
    { id: 211, name: "سيدي عكاشة", nameAscii: "Sidi Akkacha" },
    { id: 208, name: "الصبحة", nameAscii: "Sobha" },
    { id: 205, name: "تاجنة", nameAscii: "Tadjena" },
    { id: 214, name: "تلعصة", nameAscii: "Talassa" },
    { id: 206, name: "تاوقريت", nameAscii: "Taougrit" },
    { id: 202, name: "تنس", nameAscii: "Tenes" },
    { id: 220, name: "الزبوجة", nameAscii: "Zeboudja" },
  ],
  "Laghouat": [
    { id: 307, name: "عين ماضي", nameAscii: "Ain Madhi" },
    { id: 303, name: "بن ناصر بن شهرة", nameAscii: "Benacer Benchohra" },
    { id: 320, name: "العسافية", nameAscii: "El Assafia" },
    { id: 323, name: "الحويطة", nameAscii: "El Haouaita" },
    { id: 305, name: "حاسي الدلاعة", nameAscii: "Hassi Delaa" },
    { id: 306, name: "حاسي الرمل", nameAscii: "Hassi R'mel" },
    { id: 309, name: "الخنق", nameAscii: "Kheneg" },
    { id: 302, name: "قصر الحيران", nameAscii: "Ksar El Hirane" },
    { id: 301, name: "الأغواط", nameAscii: "Laghouat" },
    { id: 304, name: "سيدي مخلوف", nameAscii: "Sidi Makhlouf" },
    { id: 308, name: "تاجموت", nameAscii: "Tadjemout" },
    { id: 318, name: "تاجرونة", nameAscii: "Tadjrouna" },
  ],
  "Oum El Bouaghi": [
    { id: 408, name: "عين ببوش", nameAscii: "Ain Babouche" },
    { id: 402, name: "عين البيضاء", nameAscii: "Ain Beida" },
    { id: 415, name: "عين الديس", nameAscii: "Ain Diss" },
    { id: 425, name: "عين فكرون", nameAscii: "Ain Fekroun" },
    { id: 412, name: "عين كرشة", nameAscii: "Ain Kercha" },
    { id: 403, name: "عين مليلة", nameAscii: "Ain M'lila" },
    { id: 427, name: "عين الزيتون", nameAscii: "Ain Zitoun" },
    { id: 404, name: "بحير الشرقي", nameAscii: "Behir Chergui" },
    { id: 409, name: "بريش", nameAscii: "Berriche" },
    { id: 421, name: "بئر الشهداء", nameAscii: "Bir Chouhada" },
    { id: 411, name: "الضلعة", nameAscii: "Dhalaa" },
    { id: 424, name: "العامرية", nameAscii: "El Amiria" },
    { id: 407, name: "البلالة", nameAscii: "El Belala" },
    { id: 414, name: "الجازية", nameAscii: "El Djazia" },
    { id: 419, name: "الفجوج بوغرارة سعودي", nameAscii: "El Fedjoudj Boughrara Sa" },
    { id: 429, name: "الحرملية", nameAscii: "El Harmilia" },
    { id: 416, name: "فكيرينة", nameAscii: "Fkirina" },
    { id: 413, name: "هنشير تومغني", nameAscii: "Hanchir Toumghani" },
    { id: 422, name: "قصر الصباحي", nameAscii: "Ksar Sbahi" },
    { id: 424, name: "مسكيانة", nameAscii: "Meskiana" },
    { id: 423, name: "وادي نيني", nameAscii: "Oued Nini" },
    { id: 428, name: "أولاد قاسم", nameAscii: "Ouled Gacem" },
    { id: 410, name: "أولاد حملة", nameAscii: "Ouled Hamla" },
    { id: 420, name: "أولاد زواي", nameAscii: "Ouled Zouai" },
    { id: 401, name: "أم البواقي", nameAscii: "Oum El Bouaghi" },
    { id: 426, name: "الرحية", nameAscii: "Rahia" },
    { id: 406, name: "سيقوس", nameAscii: "Sigus" },
    { id: 417, name: "سوق نعمان", nameAscii: "Souk Naamane" },
    { id: 418, name: "الزرق", nameAscii: "Zorg" },
  ],
  "Batna": [
    { id: 519, name: "عين جاسر", nameAscii: "Ain Djasser" },
    { id: 545, name: "عين التوتة", nameAscii: "Ain Touta" },
    { id: 522, name: "عين ياقوت", nameAscii: "Ain Yagout" },
    { id: 516, name: "أريس", nameAscii: "Arris" },
    { id: 501, name: "باتنة", nameAscii: "Batna" },
    { id: 532, name: "بني فضالة الحقانية", nameAscii: "Beni Foudhala El Hakania" },
    { id: 560, name: "بولهيلات", nameAscii: "Boulhilat" },
    { id: 541, name: "بومقر", nameAscii: "Boumagueur" },
    { id: 559, name: "بومية", nameAscii: "Boumia" },
    { id: 535, name: "بوزينة", nameAscii: "Bouzina" },
    { id: 536, name: "الشمرة", nameAscii: "Chemora" },
    { id: 552, name: "شير", nameAscii: "Chir" },
    { id: 513, name: "جرمة", nameAscii: "Djerma" },
    { id: 557, name: "الحاسي", nameAscii: "El Hassi" },
    { id: 507, name: "المعذر", nameAscii: "El Madher" },
    { id: 523, name: "فسديس", nameAscii: "Fesdis" },
    { id: 531, name: "فم الطوب", nameAscii: "Foum Toub" },
    { id: 502, name: "غسيرة", nameAscii: "Ghassira" },
    { id: 539, name: "القصبات", nameAscii: "Gosbat" },
    { id: 510, name: "القيقبة", nameAscii: "Guigba" },
    { id: 546, name: "حيدوسة", nameAscii: "Hidoussa" },
    { id: 530, name: "إشمول", nameAscii: "Ichemoul" },
    { id: 511, name: "إينوغيسن", nameAscii: "Inoughissen" },
    { id: 517, name: "كيمل", nameAscii: "Kimmel" },
    { id: 528, name: "قصر بلزمة", nameAscii: "Ksar Bellezma" },
    { id: 561, name: "لارباع", nameAscii: "Larbaa" },
    { id: 558, name: "لازرو", nameAscii: "Lazrou" },
    { id: 50138, name: "لمسان", nameAscii: "Lemcene" },
    { id: 503, name: "معافة", nameAscii: "Maafa" },
    { id: 506, name: "منعة", nameAscii: "Menaa" },
    { id: 504, name: "مروانة", nameAscii: "Merouana" },
    { id: 509, name: "نقاوس", nameAscii: "N Gaous" },
    { id: 537, name: "وادي الشعبة", nameAscii: "Oued Chaaba" },
    { id: 533, name: "وادي الماء", nameAscii: "Oued El Ma" },
    { id: 548, name: "وادي الطاقة", nameAscii: "Oued Taga" },
    { id: 540, name: "أولاد عوف", nameAscii: "Ouled Aouf" },
    { id: 549, name: "أولاد فاضل", nameAscii: "Ouled Fadel" },
    { id: 520, name: "أولاد سلام", nameAscii: "Ouled Sellem" },
    { id: 553, name: "أولاد سي سليمان", nameAscii: "Ouled Si Slimane" },
    { id: 512, name: "عيون العصافير", nameAscii: "Ouyoun El Assafir" },
    { id: 525, name: "الرحبات", nameAscii: "Rahbat" },
    { id: 551, name: "رأس العيون", nameAscii: "Ras El Aioun" },
    { id: 524, name: "سفيان", nameAscii: "Sefiane" },
    { id: 505, name: "سريانة", nameAscii: "Seriana" },
    { id: 544, name: "تكوت", nameAscii: "T Kout" },
    { id: 534, name: "تالخمت", nameAscii: "Talkhamt" },
    { id: 538, name: "تاكسلانت", nameAscii: "Taxlent" },
    { id: 508, name: "تازولت", nameAscii: "Tazoult" },
    { id: 547, name: "ثنية العابد", nameAscii: "Teniet El Abed" },
    { id: 526, name: "تيغانمين", nameAscii: "Tighanimine" },
    { id: 521, name: "تغرغار", nameAscii: "Tigharghar" },
    { id: 550, name: "تيمقاد", nameAscii: "Timgad" },
    { id: 554, name: "زانة البيضاء", nameAscii: "Zanet El Beida" },
  ],
  "Béjaïa": [
    { id: 624, name: "أدكار", nameAscii: "Adekar" },
    { id: 628, name: "أيت رزين", nameAscii: "Ait R'zine" },
    { id: 647, name: "أيت إسماعيل", nameAscii: "Ait-Smail" },
    { id: 625, name: "أقبو", nameAscii: "Akbou" },
    { id: 642, name: "أكفادو", nameAscii: "Akfadou" },
    { id: 616, name: "أمالو", nameAscii: "Amalou" },
    { id: 602, name: "أميزور", nameAscii: "Amizour" },
    { id: 622, name: "أوقاس", nameAscii: "Aokas" },
    { id: 634, name: "برباشة", nameAscii: "Barbacha" },
    { id: 601, name: "بجاية", nameAscii: "Bejaia" },
    { id: 623, name: "بني جليل", nameAscii: "Beni Djellil" },
    { id: 635, name: "بني كسيلة", nameAscii: "Beni K'sila" },
    { id: 638, name: "بني مليكش", nameAscii: "Beni-Mallikeche" },
    { id: 50179, name: "بني معوش", nameAscii: "Benimaouche" },
    { id: 652, name: "بو جليل", nameAscii: "Boudjellil" },
    { id: 637, name: "بوحمزة", nameAscii: "Bouhamza" },
    { id: 648, name: "بوخليفة", nameAscii: "Boukhelifa" },
    { id: 605, name: "شلاطة", nameAscii: "Chellata" },
    { id: 629, name: "شميني", nameAscii: "Chemini" },
    { id: 620, name: "درقينة", nameAscii: "Darguina" },
    { id: 645, name: "ذراع القايد", nameAscii: "Dra El Caid" },
    { id: 640, name: "القصر", nameAscii: "El Kseur" },
    { id: 618, name: "فناية الماثن", nameAscii: "Fenaia Il Maten" },
    { id: 603, name: "فرعون", nameAscii: "Feraoun" },
    { id: 617, name: "إغيل علي", nameAscii: "Ighil-Ali" },
    { id: 615, name: "اغرم", nameAscii: "Ighram" },
    { id: 613, name: "كنديرة", nameAscii: "Kendira" },
    { id: 644, name: "خراطة", nameAscii: "Kherrata" },
    { id: 643, name: "الفلاي", nameAscii: "Leflaye" },
    { id: 609, name: "مسيسنة", nameAscii: "M'cisna" },
    { id: 641, name: "مالبو", nameAscii: "Melbou" },
    { id: 651, name: "وادي غير", nameAscii: "Oued Ghir" },
    { id: 636, name: "أوزلاقن", nameAscii: "Ouzellaguen" },
    { id: 626, name: "صدوق", nameAscii: "Seddouk" },
    { id: 621, name: "سيدي عياد", nameAscii: "Sidi Ayad" },
    { id: 639, name: "سيدي عيش", nameAscii: "Sidi-Aich" },
    { id: 612, name: "سمعون", nameAscii: "Smaoun" },
    { id: 608, name: "سوق لإثنين", nameAscii: "Souk El Tenine" },
    { id: 630, name: "سوق اوفلا", nameAscii: "Souk Oufella" },
    { id: 633, name: "تالة حمزة", nameAscii: "Tala Hamza" },
    { id: 606, name: "تامقرة", nameAscii: "Tamokra" },
    { id: 646, name: "تامريجت", nameAscii: "Tamridjet" },
    { id: 604, name: "تاوريرت إغيل", nameAscii: "Taourit Ighil" },
    { id: 631, name: "تاسكريوت", nameAscii: "Taskriout" },
    { id: 627, name: "تازمالت", nameAscii: "Tazmalt" },
    { id: 632, name: "طيبان", nameAscii: "Tibane" },
    { id: 611, name: "تيشي", nameAscii: "Tichy" },
    { id: 614, name: "تيفرة", nameAscii: "Tifra" },
    { id: 607, name: "تيمزريت", nameAscii: "Timezrit" },
    { id: 50215, name: "تينبدار", nameAscii: "Tinebdar" },
    { id: 649, name: "تيزي نبربر", nameAscii: "Tizi-N'berber" },
    { id: 619, name: "توجة", nameAscii: "Toudja" },
  ],
  "Biskra": [
    { id: 714, name: "عين الناقة", nameAscii: "Ain Naga" },
    { id: 701, name: "بسكرة", nameAscii: "Biskra" },
    { id: 727, name: "برج بن عزوز", nameAscii: "Bordj Ben Azzouz" },
    { id: 729, name: "بوشقرون", nameAscii: "Bouchakroun" },
    { id: 704, name: "شتمة", nameAscii: "Chetma" },
    { id: 716, name: "الفيض", nameAscii: "El Feidh" },
    { id: 731, name: "الغروس", nameAscii: "El Ghrous" },
    { id: 732, name: "الحاجب", nameAscii: "El Hadjab" },
    { id: 713, name: "الحوش", nameAscii: "El Haouch" },
    { id: 726, name: "فوغالة", nameAscii: "Foughala" },
    { id: 733, name: "خنقة سيدي ناجي", nameAscii: "Khenguet Sidi Nadji" },
    { id: 723, name: "ليشانة", nameAscii: "Lichana" },
    { id: 722, name: "ليوة", nameAscii: "Lioua" },
    { id: 712, name: "مشونش", nameAscii: "M'chouneche" },
    { id: 725, name: "مليلي", nameAscii: "M'lili" },
    { id: 730, name: "مخادمة", nameAscii: "Mekhadma" },
    { id: 50236, name: "المزيرعة", nameAscii: "Meziraa" },
    { id: 702, name: "أوماش", nameAscii: "Oumache" },
    { id: 724, name: "أورلال", nameAscii: "Ourlal" },
    { id: 711, name: "سيدي عقبة", nameAscii: "Sidi Okba" },
    { id: 721, name: "طولقة", nameAscii: "Tolga" },
    { id: 715, name: "زريبة الوادي", nameAscii: "Zeribet El Oued" },
  ],
  "Béchar": [
    { id: 817, name: "العبادلة", nameAscii: "Abadla" },
    { id: 801, name: "بشار", nameAscii: "Bechar" },
    { id: 821, name: "بني ونيف", nameAscii: "Beni-Ounif" },
    { id: 815, name: "بوكايس", nameAscii: "Boukais" },
    { id: 802, name: "عرق فراج", nameAscii: "Erg-Ferradj" },
    { id: 810, name: "القنادسة", nameAscii: "Kenadsa" },
    { id: 806, name: "لحمر", nameAscii: "Lahmar" },
    { id: 809, name: "مشرع هواري بومدين", nameAscii: "Machraa-Houari-Boumediene" },
    { id: 804, name: "المريجة", nameAscii: "Meridja" },
    { id: 816, name: "موغل", nameAscii: "Mogheul" },
    { id: 812, name: "تبلبالة", nameAscii: "Tabelbala" },
    { id: 813, name: "تاغيت", nameAscii: "Taghit" },
  ],
  "Blida": [
    { id: 924, name: "عين الرمانة", nameAscii: "Ain Romana" },
    { id: 921, name: "بني مراد", nameAscii: "Beni Mered" },
    { id: 919, name: "بني تامو", nameAscii: "Beni-Tamou" },
    { id: 910, name: "بن خليل", nameAscii: "Benkhelil" },
    { id: 901, name: "البليدة", nameAscii: "Blida" },
    { id: 920, name: "بوعرفة", nameAscii: "Bouarfa" },
    { id: 916, name: "بوفاريك", nameAscii: "Boufarik" },
    { id: 922, name: "بوقرة", nameAscii: "Bougara" },
    { id: 903, name: "بوعينان", nameAscii: "Bouinan" },
    { id: 902, name: "الشبلي", nameAscii: "Chebli" },
    { id: 908, name: "الشفة", nameAscii: "Chiffa" },
    { id: 906, name: "الشريعة", nameAscii: "Chrea" },
    { id: 925, name: "جبابرة", nameAscii: "Djebabra" },
    { id: 907, name: "العفرون", nameAscii: "El-Affroun" },
    { id: 923, name: "قرواو", nameAscii: "Guerrouaou" },
    { id: 909, name: "حمام ملوان", nameAscii: "Hammam Elouane" },
    { id: 917, name: "الأربعاء", nameAscii: "Larbaa" },
    { id: 914, name: "مفتاح", nameAscii: "Meftah" },
    { id: 912, name: "موزاية", nameAscii: "Mouzaia" },
    { id: 918, name: "وادي جر", nameAscii: "Oued Djer" },
    { id: 904, name: "وادي العلايق", nameAscii: "Oued El Alleug" },
    { id: 915, name: "اولاد سلامة", nameAscii: "Ouled Slama" },
    { id: 905, name: "أولاد يعيش", nameAscii: "Ouled Yaich" },
    { id: 913, name: "صوحان", nameAscii: "Souhane" },
    { id: 911, name: "الصومعة", nameAscii: "Soumaa" },
  ],
  "Bouira": [
    { id: 1027, name: "أغبالو", nameAscii: "Aghbalou" },
    { id: 1022, name: "أهل القصر", nameAscii: "Ahl El Ksar" },
    { id: 1025, name: "عين الحجر", nameAscii: "Ain El Hadjar" },
    { id: 1041, name: "عين العلوي", nameAscii: "Ain Laloui" },
    { id: 1035, name: "عين بسام", nameAscii: "Ain-Bessem" },
    { id: 1008, name: "أيت لعزيز", nameAscii: "Ait Laaziz" },
    { id: 1016, name: "أعمر", nameAscii: "Aomar" },
    { id: 1043, name: "آث منصور", nameAscii: "Ath Mansour" },
    { id: 1033, name: "بشلول", nameAscii: "Bechloul" },
    { id: 1036, name: "بئر غبالو", nameAscii: "Bir Ghbalou" },
    { id: 1018, name: "برج أوخريص", nameAscii: "Bordj Okhriss" },
    { id: 1023, name: "بودربالة", nameAscii: "Bouderbala" },
    { id: 1001, name: "البويرة", nameAscii: "Bouira" },
    { id: 1034, name: "بوكرم", nameAscii: "Boukram" },
    { id: 1017, name: "شرفة", nameAscii: "Chorfa" },
    { id: 1031, name: "الدشمية", nameAscii: "Dechmia" },
    { id: 1007, name: "ديرة", nameAscii: "Dirah" },
    { id: 1026, name: "جباحية", nameAscii: "Djebahia" },
    { id: 1019, name: "العجيبة", nameAscii: "El Adjiba" },
    { id: 1002, name: "الأسنام", nameAscii: "El Asnam" },
    { id: 1015, name: "الهاشمية", nameAscii: "El Hachimia" },
    { id: 1021, name: "الخبوزية", nameAscii: "El Khabouzia" },
    { id: 1020, name: "الحاكمية", nameAscii: "El-Hakimia" },
    { id: 1044, name: "المقراني", nameAscii: "El-Mokrani" },
    { id: 1003, name: "قرومة", nameAscii: "Guerrouma" },
    { id: 1042, name: "الحجرة الزرقاء", nameAscii: "Hadjera Zerga" },
    { id: 1012, name: "حيزر", nameAscii: "Haizer" },
    { id: 1006, name: "حنيف", nameAscii: "Hanif" },
    { id: 1005, name: "قادرية", nameAscii: "Kadiria" },
    { id: 1013, name: "الأخضرية", nameAscii: "Lakhdaria" },
    { id: 1037, name: "أمشدالة", nameAscii: "M Chedallah" },
    { id: 1014, name: "معلة", nameAscii: "Maala" },
    { id: 1039, name: "المعمورة", nameAscii: "Maamora" },
    { id: 1011, name: "مزدور", nameAscii: "Mezdour" },
    { id: 1045, name: "وادي البردي", nameAscii: "Oued El Berdi" },
    { id: 1040, name: "أولاد راشد", nameAscii: "Ouled Rached" },
    { id: 1010, name: "روراوة", nameAscii: "Raouraoua" },
    { id: 1032, name: "ريدان", nameAscii: "Ridane" },
    { id: 1030, name: "سحاريج", nameAscii: "Saharidj" },
    { id: 1004, name: "سوق الخميس", nameAscii: "Souk El Khemis" },
    { id: 1038, name: "سور الغزلان", nameAscii: "Sour El Ghozlane" },
    { id: 1009, name: "تاغزوت", nameAscii: "Taghzout" },
    { id: 1028, name: "تاقديت", nameAscii: "Taguedite" },
    { id: 50328, name: "زبربر", nameAscii: "Z'barbar" },
  ],
  "Tamanrasset": [
    { id: 50331, name: "ابلسة", nameAscii: "Abelsa" },
    { id: 1109, name: "عين امقل", nameAscii: "Ain Amguel" },
    { id: 1105, name: "أدلس", nameAscii: "Idles" },
    { id: 1101, name: "تمنراست", nameAscii: "Tamanrasset" },
    { id: 1106, name: "تاظروك", nameAscii: "Tazrouk" },
  ],
  "Tébessa": [
    { id: 1223, name: "عين الزرقاء", nameAscii: "Ain Zerga" },
    { id: 1226, name: "بجن", nameAscii: "Bedjene" },
    { id: 1217, name: "بكارية", nameAscii: "Bekkaria" },
    { id: 1214, name: "بئر الذهب", nameAscii: "Bir Dheheb" },
    { id: 1210, name: "بئر مقدم", nameAscii: "Bir Mokkadem" },
    { id: 1218, name: "بوخضرة", nameAscii: "Boukhadra" },
    { id: 1225, name: "بولحاف الدير", nameAscii: "Boulhaf Dyr" },
    { id: 1203, name: "الشريعة", nameAscii: "Cheria" },
    { id: 1211, name: "الكويف", nameAscii: "El Kouif" },
    { id: 1220, name: "الماء الابيض", nameAscii: "El Malabiod" },
    { id: 1224, name: "المريج", nameAscii: "El Meridj" },
    { id: 1227, name: "المزرعة", nameAscii: "El Mezeraa" },
    { id: 1213, name: "العقلة", nameAscii: "El Ogla" },
    { id: 1205, name: "العوينات", nameAscii: "El-Aouinet" },
    { id: 1206, name: "الحويجبات", nameAscii: "El-Houidjbet" },
    { id: 1216, name: "قريقر", nameAscii: "Guorriguer" },
    { id: 1208, name: "الحمامات", nameAscii: "Hammamet" },
    { id: 1212, name: "مرسط", nameAscii: "Morsott" },
    { id: 1219, name: "الونزة", nameAscii: "Ouenza" },
    { id: 1221, name: "أم علي", nameAscii: "Oum Ali" },
    { id: 1207, name: "صفصاف الوسرى", nameAscii: "Saf Saf El Ouesra" },
    { id: 1204, name: "سطح قنطيس", nameAscii: "Stah Guentis" },
    { id: 1201, name: "تبسة", nameAscii: "Tebessa" },
    { id: 1222, name: "ثليجان", nameAscii: "Telidjen" },
  ],
  "Tlemcen": [
    { id: 1331, name: "عين فتاح", nameAscii: "Ain Fetah" },
    { id: 1312, name: "عين فزة", nameAscii: "Ain Fezza" },
    { id: 1349, name: "عين غرابة", nameAscii: "Ain Ghoraba" },
    { id: 1353, name: "عين الكبيرة", nameAscii: "Ain Kebira" },
    { id: 1325, name: "عين النحالة", nameAscii: "Ain Nehala" },
    { id: 1303, name: "عين تالوت", nameAscii: "Ain Tellout" },
    { id: 1315, name: "عين يوسف", nameAscii: "Ain Youcef" },
    { id: 1314, name: "عمير", nameAscii: "Amieur" },
    { id: 1321, name: "العزايل", nameAscii: "Azail" },
    { id: 1318, name: "باب العسة", nameAscii: "Bab El Assa" },
    { id: 1342, name: "بني بهدل", nameAscii: "Beni Bahdel" },
    { id: 1338, name: "بني بوسعيد", nameAscii: "Beni Boussaid" },
    { id: 1348, name: "بني خلاد", nameAscii: "Beni Khellad" },
    { id: 1302, name: "بني مستر", nameAscii: "Beni Mester" },
    { id: 1336, name: "بني وارسوس", nameAscii: "Beni Ouarsous" },
    { id: 1352, name: "بني صميل", nameAscii: "Beni Smiel" },
    { id: 1317, name: "بني سنوس", nameAscii: "Beni Snous" },
    { id: 1324, name: "بن سكران", nameAscii: "Bensekrane" },
    { id: 1347, name: "بوحلو", nameAscii: "Bouhlou" },
    { id: 1350, name: "شتوان", nameAscii: "Chetouane" },
    { id: 1319, name: "دار يغمراسن", nameAscii: "Dar Yaghmoracen" },
    { id: 1309, name: "جبالة", nameAscii: "Djebala" },
    { id: 1305, name: "الفحول", nameAscii: "El Fehoul" },
    { id: 1320, name: "فلاوسن", nameAscii: "Fellaoucene" },
    { id: 1307, name: "الغزوات", nameAscii: "Ghazaouet" },
    { id: 1328, name: "حمام بوغرارة", nameAscii: "Hammam Boughrara" },
    { id: 1326, name: "الحناية", nameAscii: "Hennaya" },
    { id: 1344, name: "هنين", nameAscii: "Honnaine" },
    { id: 1330, name: "مسيردة الفواقة", nameAscii: "M'sirda Fouaga" },
    { id: 1327, name: "مغنية", nameAscii: "Maghnia" },
    { id: 1351, name: "منصورة", nameAscii: "Mansourah" },
    { id: 1339, name: "مرسى بن مهيدي", nameAscii: "Marsa Ben M'hidi" },
    { id: 1340, name: "ندرومة", nameAscii: "Nedroma" },
    { id: 1311, name: "وادي الخضر", nameAscii: "Oued Lakhdar" },
    { id: 1313, name: "أولاد ميمون", nameAscii: "Ouled Mimoun" },
    { id: 1346, name: "أولاد رياح", nameAscii: "Ouled Riyah" },
    { id: 1304, name: "الرمشي", nameAscii: "Remchi" },
    { id: 1306, name: "صبرة", nameAscii: "Sabra" },
    { id: 1322, name: "سبعة شيوخ", nameAscii: "Sebbaa Chioukh" },
    { id: 1335, name: "سبدو", nameAscii: "Sebdou" },
    { id: 1334, name: "سيدي العبدلي", nameAscii: "Sidi Abdelli" },
    { id: 1337, name: "سيدي مجاهد", nameAscii: "Sidi Medjahed" },
    { id: 1329, name: "السواحلية", nameAscii: "Souahlia" },
    { id: 1308, name: "السواني", nameAscii: "Souani" },
    { id: 1333, name: "سوق الثلاثاء", nameAscii: "Souk Tleta" },
    { id: 1323, name: "تيرني بني هديل", nameAscii: "Terny Beni Hediel" },
    { id: 1345, name: "تيانت", nameAscii: "Tianet" },
    { id: 1301, name: "تلمسان", nameAscii: "Tlemcen" },
    { id: 1316, name: "زناتة", nameAscii: "Zenata" },
  ],
  "Tiaret": [
    { id: 1403, name: "عين بوشقيف", nameAscii: "Ain Bouchekif" },
    { id: 1406, name: "عين الذهب", nameAscii: "Ain Deheb" },
    { id: 1405, name: "عين دزاريت", nameAscii: "Ain Dzarit" },
    { id: 1418, name: "عين الحديد", nameAscii: "Ain El Hadid" },
    { id: 1428, name: "عين كرمس", nameAscii: "Ain Kermes" },
    { id: 1409, name: "بوقارة", nameAscii: "Bougara" },
    { id: 1436, name: "شحيمة", nameAscii: "Chehaima" },
    { id: 1413, name: "دحموني", nameAscii: "Dahmouni" },
    { id: 1419, name: "جبيلات الرصفاء", nameAscii: "Djebilet Rosfa" },
    { id: 1424, name: "جيلالي بن عمار", nameAscii: "Djillali Ben Amar" },
    { id: 1441, name: "الفايجة", nameAscii: "Faidja" },
    { id: 1427, name: "فرندة", nameAscii: "Frenda" },
    { id: 1422, name: "قرطوفة", nameAscii: "Guertoufa" },
    { id: 1430, name: "حمادية", nameAscii: "Hamadia" },
    { id: 1429, name: "قصر الشلالة", nameAscii: "Ksar Chellala" },
    { id: 1410, name: "مادنة", nameAscii: "Madna" },
    { id: 1415, name: "مهدية", nameAscii: "Mahdia" },
    { id: 1434, name: "مشرع الصفا", nameAscii: "Mechraa Safa" },
    { id: 1408, name: "مدريسة", nameAscii: "Medrissa" },
    { id: 1402, name: "مدروسة", nameAscii: "Medroussa" },
    { id: 1421, name: "مغيلة", nameAscii: "Meghila" },
    { id: 1412, name: "ملاكو", nameAscii: "Mellakou" },
    { id: 1431, name: "الناظورة", nameAscii: "Nadorah" },
    { id: 1420, name: "النعيمة", nameAscii: "Naima" },
    { id: 1433, name: "وادي ليلي", nameAscii: "Oued Lilli" },
    { id: 1414, name: "الرحوية", nameAscii: "Rahouia" },
    { id: 1435, name: "الرشايقة", nameAscii: "Rechaiga" },
    { id: 1425, name: "السبعين", nameAscii: "Sebaine" },
    { id: 1411, name: "السبت", nameAscii: "Sebt" },
    { id: 1439, name: "سرغين", nameAscii: "Serghine" },
    { id: 1417, name: "سي عبد الغني", nameAscii: "Si Abdelghani" },
    { id: 1438, name: "سيدي عبد الرحمن", nameAscii: "Sidi Abderrahmane" },
    { id: 1404, name: "سيدي علي ملال", nameAscii: "Sidi Ali Mellal" },
    { id: 1407, name: "سيدي بختي", nameAscii: "Sidi Bakhti" },
    { id: 1423, name: "سيدي حسني", nameAscii: "Sidi Hosni" },
    { id: 1416, name: "السوقر", nameAscii: "Sougueur" },
    { id: 1432, name: "تاقدمت", nameAscii: "Tagdempt" },
    { id: 1437, name: "تخمرت", nameAscii: "Takhemaret" },
    { id: 1401, name: "تيارت", nameAscii: "Tiaret" },
    { id: 1442, name: "تيدة", nameAscii: "Tidda" },
    { id: 1426, name: "توسنينة", nameAscii: "Tousnina" },
    { id: 1440, name: "زمالة الأمير عبد القادر", nameAscii: "Zmalet El Emir Abdelkader" },
  ],
  "Tizi Ouzou": [
    { id: 1531, name: "أبي يوسف", nameAscii: "Abi-Youcef" },
    { id: 1553, name: "أغريب", nameAscii: "Aghribs" },
    { id: 1561, name: "أقني قغران", nameAscii: "Agouni-Gueghrane" },
    { id: 1502, name: "عين الحمام", nameAscii: "Ain-El-Hammam" },
    { id: 1525, name: "عين الزاوية", nameAscii: "Ain-Zaouia" },
    { id: 1535, name: "أيت عقـواشة", nameAscii: "Ait Aggouacha" },
    { id: 1565, name: "أيت بــوادو", nameAscii: "Ait Bouaddou" },
    { id: 1530, name: "أيت بومهدي", nameAscii: "Ait Boumahdi" },
    { id: 1558, name: "أيت خليلي", nameAscii: "Ait Khellili" },
    { id: 1556, name: "أيت يحي موسى", nameAscii: "Ait Yahia Moussa" },
    { id: 1539, name: "أيت عيسى ميمون", nameAscii: "Ait-Aissa-Mimoun" },
    { id: 1513, name: "أيت شافع", nameAscii: "Ait-Chafaa" },
    { id: 1528, name: "أيت محمود", nameAscii: "Ait-Mahmoud" },
    { id: 1542, name: "أيت أومالو", nameAscii: "Ait-Oumalou" },
    { id: 1567, name: "أيت تودرت", nameAscii: "Ait-Toudert" },
    { id: 1527, name: "أيت يحيى", nameAscii: "Ait-Yahia" },
    { id: 1503, name: "اقبيل", nameAscii: "Akbil" },
    { id: 1544, name: "أقرو", nameAscii: "Akerrou" },
    { id: 1566, name: "أسي يوسف", nameAscii: "Assi-Youcef" },
    { id: 1518, name: "عزازقة", nameAscii: "Azazga" },
    { id: 1537, name: "أزفون", nameAscii: "Azeffoun" },
    { id: 1516, name: "بنــــي زمنزار", nameAscii: "Beni Zmenzer" },
    { id: 1515, name: "بني عيسي", nameAscii: "Beni-Aissi" },
    { id: 1532, name: "بني دوالة", nameAscii: "Beni-Douala" },
    { id: 1552, name: "بني يني", nameAscii: "Beni-Yenni" },
    { id: 1546, name: "بني زيكــي", nameAscii: "Beni-Zikki" },
    { id: 1540, name: "بوغني", nameAscii: "Boghni" },
    { id: 1555, name: "بوجيمة", nameAscii: "Boudjima" },
    { id: 1512, name: "بونوح", nameAscii: "Bounouh" },
    { id: 1534, name: "بوزقــن", nameAscii: "Bouzeguene" },
    { id: 1547, name: "ذراع بن خدة", nameAscii: "Draa-Ben-Khedda" },
    { id: 1510, name: "ذراع الميزان", nameAscii: "Draa-El-Mizan" },
    { id: 1504, name: "فريحة", nameAscii: "Freha" },
    { id: 1514, name: "فريقات", nameAscii: "Frikat" },
    { id: 1560, name: "إبودرارن", nameAscii: "Iboudrarene" },
    { id: 1549, name: "إيجــار", nameAscii: "Idjeur" },
    { id: 1517, name: "إفــرحــونان", nameAscii: "Iferhounene" },
    { id: 1541, name: "إيفيغاء", nameAscii: "Ifigha" },
    { id: 1554, name: "إفليـــسن", nameAscii: "Iflissen" },
    { id: 1533, name: "إيلـيــلتـن", nameAscii: "Illilten" },
    { id: 1519, name: "إيلولة أومـــالو", nameAscii: "Illoula Oumalou" },
    { id: 1563, name: "إمســوحال", nameAscii: "Imsouhal" },
    { id: 1507, name: "إيرجـــن", nameAscii: "Irdjen" },
    { id: 1521, name: "الأربعــاء ناث إيراثن", nameAscii: "Larbaa Nath Irathen" },
    { id: 1526, name: "مكيرة", nameAscii: "M'kira" },
    { id: 1529, name: "معـــاتقة", nameAscii: "Maatkas" },
    { id: 1509, name: "ماكودة", nameAscii: "Makouda" },
    { id: 1506, name: "مشطراس", nameAscii: "Mechtras" },
    { id: 1550, name: "مقــلع", nameAscii: "Mekla" },
    { id: 1562, name: "ميزرانـــة", nameAscii: "Mizrana" },
    { id: 1548, name: "واسيف", nameAscii: "Ouacif" },
    { id: 1536, name: "واضية", nameAscii: "Ouadhias" },
    { id: 1524, name: "واقنون", nameAscii: "Ouaguenoun" },
    { id: 1559, name: "سيدي نعمان", nameAscii: "Sidi Namane" },
    { id: 2840, name: "صوامـــع", nameAscii: "Souama" },
    { id: 1564, name: "تادمايت", nameAscii: "Tadmait" },
    { id: 1538, name: "تيقـزيرت", nameAscii: "Tigzirt" },
    { id: 1508, name: "تيمـيزار", nameAscii: "Timizart" },
    { id: 1543, name: "تيرمتين", nameAscii: "Tirmitine" },
    { id: 1551, name: "تيزي نثلاثة", nameAscii: "Tizi N'tleta" },
    { id: 1511, name: "تيزي غنيف", nameAscii: "Tizi-Gheniff" },
    { id: 1501, name: "تيزي وزو", nameAscii: "Tizi-Ouzou" },
    { id: 1522, name: "تيزي راشد", nameAscii: "Tizi-Rached" },
    { id: 1520, name: "إعــكورن", nameAscii: "Yakourene" },
    { id: 1545, name: "يطــافن", nameAscii: "Yatafene" },
    { id: 1523, name: "زكري", nameAscii: "Zekri" },
  ],
  "Alger": [
    { id: 1657, name: "عين بنيان", nameAscii: "Ain Benian" },
    { id: 1641, name: "عين طاية", nameAscii: "Ain Taya" },
    { id: 1601, name: "الجزائر الوسطى", nameAscii: "Alger Centre" },
    { id: 1605, name: "باب الوادي", nameAscii: "Bab El Oued" },
    { id: 1621, name: "باب الزوار", nameAscii: "Bab Ezzouar" },
    { id: 1647, name: "بابا حسن", nameAscii: "Baba Hassen" },
    { id: 1619, name: "باش جراح", nameAscii: "Bachedjerah" },
    { id: 1614, name: "براقي", nameAscii: "Baraki" },
    { id: 1622, name: "ابن عكنون", nameAscii: "Ben Aknoun" },
    { id: 1632, name: "بني مسوس", nameAscii: "Beni Messous" },
    { id: 1609, name: "بئر مراد رايس", nameAscii: "Bir Mourad Rais" },
    { id: 1636, name: "بئر توتة", nameAscii: "Bir Touta" },
    { id: 1612, name: "بئر خادم", nameAscii: "Birkhadem" },
    { id: 50534, name: "بولوغين بن زيري", nameAscii: "Bologhine Ibnou Ziri" },
    { id: 1642, name: "برج البحري", nameAscii: "Bordj El Bahri" },
    { id: 1630, name: "برج الكيفان", nameAscii: "Bordj El Kiffan" },
    { id: 1616, name: "بوروبة", nameAscii: "Bourouba" },
    { id: 1611, name: "بوزريعة", nameAscii: "Bouzareah" },
    { id: 1607, name: "القصبة", nameAscii: "Casbah" },
    { id: 1652, name: "الشراقة", nameAscii: "Cheraga" },
    { id: 1620, name: "الدار البيضاء", nameAscii: "Dar El Beida" },
    { id: 1623, name: "دالي ابراهيم", nameAscii: "Dely Ibrahim" },
    { id: 1626, name: "جسر قسنطينة", nameAscii: "Djasr Kasentina" },
    { id: 1648, name: "الدويرة", nameAscii: "Douira" },
    { id: 1649, name: "الدرارية", nameAscii: "Draria" },
    { id: 1654, name: "العاشور", nameAscii: "El Achour" },
    { id: 1610, name: "الابيار", nameAscii: "El Biar" },
    { id: 1613, name: "الحراش", nameAscii: "El Harrach" },
    { id: 1603, name: "المدنية", nameAscii: "El Madania" },
    { id: 1631, name: "المغارية", nameAscii: "El Magharia" },
    { id: 1643, name: "المرسى", nameAscii: "El Marsa" },
    { id: 1627, name: "المرادية", nameAscii: "El Mouradia" },
    { id: 1624, name: "الحمامات", nameAscii: "Hammamet" },
    { id: 1639, name: "هراوة", nameAscii: "Herraoua" },
    { id: 1617, name: "حسين داي", nameAscii: "Hussein Dey" },
    { id: 1628, name: "حيدرة", nameAscii: "Hydra" },
    { id: 1656, name: "الخرايسية", nameAscii: "Khraissia" },
    { id: 1618, name: "القبة", nameAscii: "Kouba" },
    { id: 1633, name: "الكاليتوس", nameAscii: "Les Eucalyptus" },
    { id: 1647, name: "المعالمة", nameAscii: "Maalma" },
    { id: 50561, name: "محمد بلوزداد", nameAscii: "Mohamed Belouzdad" },
    { id: 1629, name: "المحمدية", nameAscii: "Mohammadia" },
    { id: 1608, name: "وادي قريش", nameAscii: "Oued Koriche" },
    { id: 1615, name: "وادي السمار", nameAscii: "Oued Smar" },
    { id: 1635, name: "اولاد شبل", nameAscii: "Ouled Chebel" },
    { id: 1651, name: "اولاد فايت", nameAscii: "Ouled Fayet" },
    { id: 1648, name: "الرحمانية", nameAscii: "Rahmania" },
    { id: 1625, name: "الرايس حميدو", nameAscii: "Rais Hamidou" },
    { id: 1640, name: "رغاية", nameAscii: "Reghaia" },
    { id: 1638, name: "الرويبة", nameAscii: "Rouiba" },
    { id: 1645, name: "السحاولة", nameAscii: "Sehaoula" },
    { id: 1602, name: "سيدي امحمد", nameAscii: "Sidi M'hamed" },
    { id: 1637, name: "سيدي موسى", nameAscii: "Sidi Moussa" },
    { id: 1649, name: "سويدانية", nameAscii: "Souidania" },
    { id: 1645, name: "سطاوالي", nameAscii: "Staoueli" },
    { id: 1634, name: "تسالة المرجة", nameAscii: "Tessala El Merdja" },
    { id: 1646, name: "زرالدة", nameAscii: "Zeralda" },
  ],
  "Djelfa": [
    { id: 1723, name: "عين الشهداء", nameAscii: "Ain Chouhada" },
    { id: 1730, name: "عين الإبل", nameAscii: "Ain El Ibel" },
    { id: 1705, name: "عين معبد", nameAscii: "Ain Maabed" },
    { id: 1727, name: "بن يعقوب", nameAscii: "Benyagoub" },
    { id: 1726, name: "الشارف", nameAscii: "Charef" },
    { id: 1725, name: "دار الشيوخ", nameAscii: "Dar Chioukh" },
    { id: 1701, name: "الجلفة", nameAscii: "Djelfa" },
    { id: 1715, name: "دويس", nameAscii: "Douis" },
    { id: 1703, name: "القديد", nameAscii: "El Guedid" },
    { id: 1714, name: "الادريسية", nameAscii: "El Idrissia" },
    { id: 1704, name: "حاسي بحبح", nameAscii: "Hassi Bahbah" },
    { id: 1716, name: "حاسي العش", nameAscii: "Hassi El Euch" },
    { id: 1713, name: "مليليحة", nameAscii: "M'liliha" },
    { id: 1702, name: "مجبارة", nameAscii: "Moudjebara" },
    { id: 1712, name: "سيدي بايزيد", nameAscii: "Sidi Baizid" },
    { id: 1736, name: "تعظميت", nameAscii: "Taadmit" },
    { id: 1728, name: "زعفران", nameAscii: "Zaafrane" },
    { id: 1710, name: "زكار", nameAscii: "Zaccar" },
  ],
  "Jijel": [
    { id: 1826, name: "برج الطهر", nameAscii: "Bordj T'har" },
    { id: 1822, name: "بودريعة بني ياجيس", nameAscii: "Boudria Beniyadjis" },
    { id: 1816, name: "بوراوي بلهادف", nameAscii: "Bouraoui Belhadef" },
    { id: 1819, name: "بوسيف أولاد عسكر", nameAscii: "Boussif Ouled Askeur" },
    { id: 1808, name: "الشحنة", nameAscii: "Chahna" },
    { id: 1807, name: "الشقفة", nameAscii: "Chekfa" },
    { id: 1825, name: "الجمعة بني حبيبي", nameAscii: "Djemaa Beni Habibi" },
    { id: 1817, name: "جيملة", nameAscii: "Djimla" },
    { id: 1812, name: "العنصر", nameAscii: "El Ancer" },
    { id: 1803, name: "العوانة", nameAscii: "El Aouana" },
    { id: 1820, name: "القنار نشفي", nameAscii: "El Kennar Nouchfi" },
    { id: 1809, name: "الميلية", nameAscii: "El Milia" },
    { id: 1806, name: "الامير عبد القادر", nameAscii: "Emir Abdelkader" },
    { id: 50613, name: "أراقن سويسي", nameAscii: "Erraguene Souissi" },
    { id: 1815, name: "غبالة", nameAscii: "Ghebala" },
    { id: 1801, name: "جيجل", nameAscii: "Jijel" },
    { id: 1814, name: "قاوس", nameAscii: "Kaous" },
    { id: 1823, name: "خيري واد عجول", nameAscii: "Khiri Oued Adjoul" },
    { id: 1828, name: "وجانة", nameAscii: "Oudjana" },
    { id: 1827, name: "أولاد رابح", nameAscii: "Ouled Rabah" },
    { id: 1821, name: "أولاد يحيى خدروش", nameAscii: "Ouled Yahia Khadrouch" },
    { id: 1818, name: "سلمى بن زيادة", nameAscii: "Selma Benziada" },
    { id: 1811, name: "السطارة", nameAscii: "Settara" },
    { id: 1813, name: "سيدي عبد العزيز", nameAscii: "Sidi Abdelaziz" },
    { id: 1810, name: "سيدي معروف", nameAscii: "Sidi Marouf" },
    { id: 1805, name: "الطاهير", nameAscii: "Taher" },
    { id: 1824, name: "تاكسنة", nameAscii: "Texenna" },
    { id: 1804, name: "زيامة منصورية", nameAscii: "Ziama Mansouriah" },
  ],
  "Sétif": [
    { id: 1914, name: "عين عباسة", nameAscii: "Ain Abessa" },
    { id: 1926, name: "عين أرنات", nameAscii: "Ain Arnat" },
    { id: 1940, name: "عين أزال", nameAscii: "Ain Azel" },
    { id: 1902, name: "عين الكبيرة", nameAscii: "Ain El Kebira" },
    { id: 1918, name: "عين الحجر", nameAscii: "Ain Lahdjar" },
    { id: 1928, name: "عين ولمان", nameAscii: "Ain Oulmene" },
    { id: 1913, name: "عين لقراج", nameAscii: "Ain-Legradj" },
    { id: 1906, name: "عين الروى", nameAscii: "Ain-Roua" },
    { id: 1949, name: "عين السبت", nameAscii: "Ain-Sebt" },
    { id: 1951, name: "أيت نوال مزادة", nameAscii: "Ait Naoual Mezada" },
    { id: 1954, name: "ايت تيزي", nameAscii: "Ait-Tizi" },
    { id: 1927, name: "عموشة", nameAscii: "Amoucha" },
    { id: 1916, name: "بابور", nameAscii: "Babor" },
    { id: 1931, name: "بازر سكرة", nameAscii: "Bazer-Sakra" },
    { id: 1929, name: "بيضاء برج", nameAscii: "Beidha Bordj" },
    { id: 1925, name: "بلاعة", nameAscii: "Bellaa" },
    { id: 1909, name: "بني شبانة", nameAscii: "Beni Chebana" },
    { id: 1944, name: "بني فودة", nameAscii: "Beni Fouda" },
    { id: 1922, name: "بني ورتيلان", nameAscii: "Beni Ourtilane" },
    { id: 1953, name: "بني وسين", nameAscii: "Beni Oussine" },
    { id: 1903, name: "بني عزيز", nameAscii: "Beni-Aziz" },
    { id: 1946, name: "بني موحلي", nameAscii: "Beni-Mouhli" },
    { id: 1934, name: "بئر حدادة", nameAscii: "Bir Haddada" },
    { id: 1908, name: "بئر العرش", nameAscii: "Bir-El-Arch" },
    { id: 1930, name: "بوعنداس", nameAscii: "Bouandas" },
    { id: 1943, name: "بوقاعة", nameAscii: "Bougaa" },
    { id: 1919, name: "بوسلام", nameAscii: "Bousselam" },
    { id: 1905, name: "بوطالب", nameAscii: "Boutaleb" },
    { id: 1915, name: "الدهامشة", nameAscii: "Dehamcha" },
    { id: 1921, name: "جميلة", nameAscii: "Djemila" },
    { id: 1907, name: "ذراع قبيلة", nameAscii: "Draa-Kebila" },
    { id: 1920, name: "العلمة", nameAscii: "El Eulma" },
    { id: 1937, name: "أوريسيا", nameAscii: "El Ouricia" },
    { id: 1959, name: "الولجة", nameAscii: "El-Ouldja" },
    { id: 1948, name: "قلال", nameAscii: "Guellal" },
    { id: 1956, name: "قلتة زرقاء", nameAscii: "Guelta Zerka" },
    { id: 1941, name: "قنزات", nameAscii: "Guenzet" },
    { id: 1917, name: "قجال", nameAscii: "Guidjel" },
    { id: 1932, name: "حمام السخنة", nameAscii: "Hamam Soukhna" },
    { id: 1911, name: "الحامة", nameAscii: "Hamma" },
    { id: 1950, name: "حمام قرقور", nameAscii: "Hammam Guergour" },
    { id: 1936, name: "حربيل", nameAscii: "Harbil" },
    { id: 1952, name: "قصر الابطال", nameAscii: "Kasr El Abtal" },
    { id: 1912, name: "معاوية", nameAscii: "Maaouia" },
    { id: 1955, name: "ماوكلان", nameAscii: "Maouaklane" },
    { id: 1933, name: "مزلوق", nameAscii: "Mezloug" },
    { id: 1957, name: "واد البارد", nameAscii: "Oued El Bared" },
    { id: 1924, name: "أولاد عدوان", nameAscii: "Ouled Addouane" },
    { id: 1947, name: "أولاد صابر", nameAscii: "Ouled Sabor" },
    { id: 1904, name: "أولاد سي أحمد", nameAscii: "Ouled Si Ahmed" },
    { id: 1910, name: "أولاد تبان", nameAscii: "Ouled Tebben" },
    { id: 1923, name: "الرصفة", nameAscii: "Rosfa" },
    { id: 1939, name: "صالح باي", nameAscii: "Salah Bey" },
    { id: 1935, name: "سرج الغول", nameAscii: "Serdj-El-Ghoul" },
    { id: 1901, name: "سطيف", nameAscii: "Setif" },
    { id: 1945, name: "تاشودة", nameAscii: "Tachouda" },
    { id: 1942, name: "تالة إيفاسن", nameAscii: "Tala-Ifacene" },
    { id: 1958, name: "الطاية", nameAscii: "Taya" },
    { id: 1960, name: "التلة", nameAscii: "Tella" },
    { id: 1938, name: "تيزي نبشار", nameAscii: "Tizi N'bechar" },
  ],
  "Saïda": [
    { id: 2003, name: "عين الحجر", nameAscii: "Ain El Hadjar" },
    { id: 2013, name: "عين السخونة", nameAscii: "Ain Sekhouna" },
    { id: 2016, name: "عين السلطان", nameAscii: "Ain Soltane" },
    { id: 2002, name: "دوي ثابت", nameAscii: "Doui Thabet" },
    { id: 2010, name: "الحساسنة", nameAscii: "El Hassasna" },
    { id: 2007, name: "هونت", nameAscii: "Hounet" },
    { id: 2011, name: "المعمورة", nameAscii: "Maamora" },
    { id: 2005, name: "مولاي العربي", nameAscii: "Moulay Larbi" },
    { id: 2612, name: "أولاد إبراهيم", nameAscii: "Ouled Brahim" },
    { id: 2004, name: "أولاد خالد", nameAscii: "Ouled Khaled" },
    { id: 2001, name: "سعيدة", nameAscii: "Saida" },
    { id: 2012, name: "سيدي احمد", nameAscii: "Sidi Ahmed" },
    { id: 2008, name: "سيدي عمر", nameAscii: "Sidi Amar" },
    { id: 2009, name: "سيدي بوبكر", nameAscii: "Sidi Boubekeur" },
    { id: 2015, name: "تيرسين", nameAscii: "Tircine" },
    { id: 2006, name: "يوب", nameAscii: "Youb" },
  ],
  "Skikda": [
    { id: 2122, name: "عين بوزيان", nameAscii: "Ain Bouziane" },
    { id: 2106, name: "عين شرشار", nameAscii: "Ain Charchar" },
    { id: 2127, name: "عين قشرة", nameAscii: "Ain Kechra" },
    { id: 2102, name: "عين زويت", nameAscii: "Ain Zouit" },
    { id: 2104, name: "عزابة", nameAscii: "Azzaba" },
    { id: 2107, name: "بكوش لخضر", nameAscii: "Bekkouche Lakhdar" },
    { id: 2108, name: "بن عزوز", nameAscii: "Ben Azzouz" },
    { id: 2124, name: "بني بشير", nameAscii: "Beni Bechir" },
    { id: 2121, name: "بني ولبان", nameAscii: "Beni Oulbane" },
    { id: 2111, name: "بني زيد", nameAscii: "Beni Zid" },
    { id: 2129, name: "بين الويدان", nameAscii: "Bin El Ouiden" },
    { id: 2134, name: "بوشطاطة", nameAscii: "Bouchetata" },
    { id: 2131, name: "الشرايع", nameAscii: "Cheraia" },
    { id: 2110, name: "القل", nameAscii: "Collo" },
    { id: 2105, name: "جندل سعدي محمد", nameAscii: "Djendel Saadi Mohamed" },
    { id: 2116, name: "الحروش", nameAscii: "El Arrouch" },
    { id: 2133, name: "الغدير", nameAscii: "El Ghedir" },
    { id: 2103, name: "الحدائق", nameAscii: "El Hadaiek" },
    { id: 2138, name: "المرسى", nameAscii: "El Marsa" },
    { id: 2120, name: "مجاز الدشيش", nameAscii: "Emjez Edchich" },
    { id: 2109, name: "السبت", nameAscii: "Es Sebt" },
    { id: 2130, name: "فلفلة", nameAscii: "Filfila" },
    { id: 2137, name: "حمادي كرومة", nameAscii: "Hammadi Krouma" },
    { id: 2132, name: "قنواع", nameAscii: "Kanoua" },
    { id: 2112, name: "الكركرة", nameAscii: "Kerkara" },
    { id: 2136, name: "خناق مايو", nameAscii: "Khenag Maoune" },
    { id: 2114, name: "وادي الزهور", nameAscii: "Oued Zhour" },
    { id: 2135, name: "الولجة بولبلوط", nameAscii: "Ouldja Boulbalout" },
    { id: 2113, name: "أولاد عطية", nameAscii: "Ouled Attia" },
    { id: 2118, name: "أولاد حبابة", nameAscii: "Ouled Habbaba" },
    { id: 2128, name: "أم الطوب", nameAscii: "Oum Toub" },
    { id: 2123, name: "رمضان جمال", nameAscii: "Ramdane Djamel" },
    { id: 2125, name: "صالح بو الشعور", nameAscii: "Salah Bouchaour" },
    { id: 2119, name: "سيدي مزغيش", nameAscii: "Sidi Mezghiche" },
    { id: 2101, name: "سكيكدة", nameAscii: "Skikda" },
    { id: 2126, name: "تمالوس", nameAscii: "Tamalous" },
    { id: 2117, name: "زردازة", nameAscii: "Zerdezas" },
    { id: 2115, name: "الزيتونة", nameAscii: "Zitouna" },
  ],
  "Sidi Bel Abbès": [
    { id: 2228, name: "عين البرد", nameAscii: "Ain El Berd" },
    { id: 2225, name: "عين قادة", nameAscii: "Ain Kada" },
    { id: 2215, name: "عين الثريد", nameAscii: "Ain Thrid" },
    { id: 2224, name: "عين تندمين", nameAscii: "Ain Tindamine" },
    { id: 2230, name: "عين أدن", nameAscii: "Ain- Adden" },
    { id: 2212, name: "العمارنة", nameAscii: "Amarnas" },
    { id: 2209, name: "بضرابين المقراني", nameAscii: "Bedrabine El Mokrani" },
    { id: 2242, name: "بلعربي", nameAscii: "Belarbi" },
    { id: 2245, name: "بن باديس", nameAscii: "Ben Badis" },
    { id: 2251, name: "بن عشيبة شلية", nameAscii: "Benachiba Chelia" },
    { id: 2248, name: "بئر الحمام", nameAscii: "Bir El Hammam" },
    { id: 2238, name: "بوجبهة البرج", nameAscii: "Boudjebaa El Bordj" },
    { id: 2207, name: "بوخنفيس", nameAscii: "Boukhanefis" },
    { id: 2247, name: "شيطوان البلايلة", nameAscii: "Chetouane Belaila" },
    { id: 2232, name: "الضاية", nameAscii: "Dhaya" },
    { id: 2219, name: "الحصيبة", nameAscii: "El Hacaiba" },
    { id: 2252, name: "حاسي دحو", nameAscii: "Hassi Dahou" },
    { id: 2220, name: "حاسي زهانة", nameAscii: "Hassi Zahana" },
    { id: 2234, name: "لمطار", nameAscii: "Lamtar" },
    { id: 2226, name: "مسيد", nameAscii: "M'cid" },
    { id: 2216, name: "مكدرة", nameAscii: "Makedra" },
    { id: 2210, name: "مرحوم", nameAscii: "Marhoum" },
    { id: 2222, name: "مرين", nameAscii: "Merine" },
    { id: 2206, name: "مزاورو", nameAscii: "Mezaourou" },
    { id: 2204, name: "مصطفى بن ابراهيم", nameAscii: "Mostefa Ben Brahim" },
    { id: 2218, name: "مولاي سليسن", nameAscii: "Moulay Slissen" },
    { id: 2237, name: "وادي السبع", nameAscii: "Oued Sebaa" },
    { id: 2243, name: "وادي سفيون", nameAscii: "Oued Sefioun" },
    { id: 2231, name: "وادي تاوريرة", nameAscii: "Oued Taourira" },
    { id: 2223, name: "راس الماء", nameAscii: "Ras El Ma" },
    { id: 2250, name: "رجم دموش", nameAscii: "Redjem Demouche" },
    { id: 2239, name: "السهالة الثورة", nameAscii: "Sehala Thaoura" },
    { id: 2229, name: "سفيزف", nameAscii: "Sfisef" },
    { id: 2246, name: "سيدي علي بن يوب", nameAscii: "Sidi Ali Benyoub" },
    { id: 2208, name: "سيدي علي بوسيدي", nameAscii: "Sidi Ali Boussidi" },
    { id: 2201, name: "سيدي بلعباس", nameAscii: "Sidi Bel-Abbes" },
    { id: 2203, name: "سيدي ابراهيم", nameAscii: "Sidi Brahim" },
    { id: 2235, name: "سيدي شعيب", nameAscii: "Sidi Chaib" },
    { id: 2236, name: "سيدي دحو الزاير", nameAscii: "Sidi Dahou Zairs" },
    { id: 2241, name: "سيدي حمادوش", nameAscii: "Sidi Hamadouche" },
    { id: 2227, name: "سيدي خالد", nameAscii: "Sidi Khaled" },
    { id: 2214, name: "سيدي لحسن", nameAscii: "Sidi Lahcene" },
    { id: 2240, name: "سيدي يعقوب", nameAscii: "Sidi Yacoub" },
    { id: 2221, name: "طابية", nameAscii: "Tabia" },
    { id: 2249, name: "تاودموت", nameAscii: "Taoudmout" },
    { id: 2211, name: "تفسور", nameAscii: "Tefessour" },
    { id: 2244, name: "تغاليمت", nameAscii: "Teghalimet" },
    { id: 2205, name: "تلاغ", nameAscii: "Telagh" },
    { id: 2217, name: "تنيرة", nameAscii: "Tenira" },
    { id: 2202, name: "تسالة", nameAscii: "Tessala" },
    { id: 2213, name: "تلموني", nameAscii: "Tilmouni" },
    { id: 2233, name: "زروالة", nameAscii: "Zerouala" },
  ],
  "Annaba": [
    { id: 2309, name: "عين الباردة", nameAscii: "Ain El Berda" },
    { id: 2301, name: "عنابة", nameAscii: "Annaba" },
    { id: 2302, name: "برحال", nameAscii: "Berrahal" },
    { id: 2310, name: "شطايبي", nameAscii: "Chetaibi" },
    { id: 2307, name: "الشرفة", nameAscii: "Cheurfa" },
    { id: 2305, name: "البوني", nameAscii: "El Bouni" },
    { id: 2303, name: "الحجار", nameAscii: "El Hadjar" },
    { id: 2306, name: "واد العنب", nameAscii: "Oued El Aneb" },
    { id: 2308, name: "سرايدي", nameAscii: "Seraidi" },
    { id: 2311, name: "سيدي عمار", nameAscii: "Sidi Amar" },
    { id: 2312, name: "التريعات", nameAscii: "Treat" },
  ],
  "Guelma": [
    { id: 2414, name: "عين بن بيضاء", nameAscii: "Ain Ben Beida" },
    { id: 2423, name: "عين العربي", nameAscii: "Ain Larbi" },
    { id: 2413, name: "عين مخلوف", nameAscii: "Ain Makhlouf" },
    { id: 2432, name: "عين رقادة", nameAscii: "Ain Regada" },
    { id: 2407, name: "عين صندل", nameAscii: "Ain Sandel" },
    { id: 2410, name: "بلخير", nameAscii: "Belkheir" },
    { id: 2411, name: "بن جراح", nameAscii: "Bendjarah" },
    { id: 2416, name: "بني مزلين", nameAscii: "Beni Mezline" },
    { id: 2421, name: "برج صباط", nameAscii: "Bordj Sabath" },
    { id: 2417, name: "بوحشانة", nameAscii: "Bou Hachana" },
    { id: 2412, name: "بوحمدان", nameAscii: "Bou Hamdane" },
    { id: 2403, name: "بوعاتي محمود", nameAscii: "Bouati Mahmoud" },
    { id: 2425, name: "بوشقوف", nameAscii: "Bouchegouf" },
    { id: 2431, name: "بومهرة أحمد", nameAscii: "Boumahra Ahmed" },
    { id: 2409, name: "الدهوارة", nameAscii: "Dahouara" },
    { id: 2434, name: "جبالة الخميسي", nameAscii: "Djeballah Khemissi" },
    { id: 2420, name: "الفجوج", nameAscii: "El Fedjoudj" },
    { id: 2418, name: "قلعة بوصبع", nameAscii: "Guelaat Bou Sbaa" },
    { id: 2401, name: "قالمة", nameAscii: "Guelma" },
    { id: 2419, name: "حمام دباغ", nameAscii: "Hammam Debagh" },
    { id: 2422, name: "حمام النبايل", nameAscii: "Hammam N'bail" },
    { id: 2426, name: "هيليوبوليس", nameAscii: "Heliopolis" },
    { id: 2427, name: "هواري بومدين", nameAscii: "Houari Boumedienne" },
    { id: 2415, name: "لخزارة", nameAscii: "Khezaras" },
    { id: 2424, name: "مجاز عمار", nameAscii: "Medjez Amar" },
    { id: 2430, name: "مجاز الصفاء", nameAscii: "Medjez Sfa" },
    { id: 2402, name: "نشماية", nameAscii: "Nechmaya" },
    { id: 2433, name: "وادي الشحم", nameAscii: "Oued Cheham" },
    { id: 2406, name: "وادي فراغة", nameAscii: "Oued Ferragha" },
    { id: 2404, name: "وادي الزناتي", nameAscii: "Oued Zenati" },
    { id: 2408, name: "رأس العقبة", nameAscii: "Ras El Agba" },
    { id: 2428, name: "الركنية", nameAscii: "Roknia" },
    { id: 2429, name: "سلاوة عنونة", nameAscii: "Sellaoua Announa" },
    { id: 2405, name: "تاملوكة", nameAscii: "Tamlouka" },
  ],
  "Constantine": [
    { id: 2507, name: "عين عبيد", nameAscii: "Ain Abid" },
    { id: 2510, name: "عين السمارة", nameAscii: "Ain Smara" },
    { id: 2508, name: "بني حميدان", nameAscii: "Beni Hamidane" },
    { id: 2501, name: "قسنطينة", nameAscii: "Constantine" },
    { id: 2505, name: "ديدوش مراد", nameAscii: "Didouche Mourad" },
    { id: 2506, name: "الخروب", nameAscii: "El Khroub" },
    { id: 2502, name: "حامة بوزيان", nameAscii: "Hamma Bouziane" },
    { id: 2512, name: "ابن زياد", nameAscii: "Ibn Ziad" },
    { id: 2511, name: "بوجريو مسعود", nameAscii: "Messaoud Boudjeriou" },
    { id: 2509, name: "أولاد رحمون", nameAscii: "Ouled Rahmoun" },
    { id: 2504, name: "زيغود يوسف", nameAscii: "Zighoud Youcef" },
  ],
  "Médéa": [
    { id: 2605, name: "العيساوية", nameAscii: "Aissaouia" },
    { id: 2624, name: "بعطة", nameAscii: "Baata" },
    { id: 2630, name: "بن شكاو", nameAscii: "Ben Chicao" },
    { id: 2646, name: "بني سليمان", nameAscii: "Beni Slimane" },
    { id: 2647, name: "البرواقية", nameAscii: "Berrouaghia" },
    { id: 2656, name: "بئر بن عابد", nameAscii: "Bir Ben Laabed" },
    { id: 2659, name: "بوعيشون", nameAscii: "Bouaichoune" },
    { id: 2621, name: "بوشراحيل", nameAscii: "Bouchrahil" },
    { id: 2619, name: "بوسكن", nameAscii: "Bouskene" },
    { id: 2637, name: "جواب", nameAscii: "Djouab" },
    { id: 2654, name: "ذراع السمار", nameAscii: "Draa Esmar" },
    { id: 2636, name: "العزيزية", nameAscii: "El Azizia" },
    { id: 2609, name: "القلب الكبير", nameAscii: "El Guelbelkebir" },
    { id: 2616, name: "الحمدانية", nameAscii: "El Hamdania" },
    { id: 2616, name: "الحوضان", nameAscii: "El Haoudane" },
    { id: 2607, name: "العمارية", nameAscii: "El Omaria" },
    { id: 2660, name: "حناشة", nameAscii: "Hannacha" },
    { id: 2663, name: "خمس جوامع", nameAscii: "Khams Djouamaa" },
    { id: 2639, name: "مغراوة", nameAscii: "Maghraoua" },
    { id: 2601, name: "المدية", nameAscii: "Medea" },
    { id: 2662, name: "مجبر", nameAscii: "Medjebar" },
    { id: 2611, name: "مزغنة", nameAscii: "Mezerana" },
    { id: 2650, name: "ميهوب", nameAscii: "Mihoub" },
    { id: 2643, name: "عوامري", nameAscii: "Ouamri" },
    { id: 2629, name: "وادي حربيل", nameAscii: "Oued Harbil" },
    { id: 2627, name: "أولاد بوعشرة", nameAscii: "Ouled Bouachra" },
    { id: 2612, name: "أولاد إبراهيم", nameAscii: "Ouled Brahim" },
    { id: 2606, name: "أولاد دايد", nameAscii: "Ouled Deid" },
    { id: 2602, name: "وزرة", nameAscii: "Ouzera" },
    { id: 2620, name: "الربعية", nameAscii: "Rebaia" },
    { id: 2661, name: "سدراية", nameAscii: "Sedraya" },
    { id: 2648, name: "سغوان", nameAscii: "Seghouane" },
    { id: 2644, name: "سي المحجوب", nameAscii: "Si Mahdjoub" },
    { id: 2626, name: "سيدي نعمان", nameAscii: "Sidi Naamane" },
    { id: 2655, name: "سيدي الربيع", nameAscii: "Sidi Rabie" },
    { id: 2628, name: "سيدي زهار", nameAscii: "Sidi Zahar" },
    { id: 2614, name: "سيدي زيان", nameAscii: "Sidi Ziane" },
    { id: 2633, name: "السواقي", nameAscii: "Souagui" },
    { id: 2652, name: "تابلاط", nameAscii: "Tablat" },
    { id: 2615, name: "تمسقيدة", nameAscii: "Tamesguida" },
    { id: 2613, name: "تيزي مهدي", nameAscii: "Tizi Mahdi" },
    { id: 2645, name: "ثلاث دوائر", nameAscii: "Tletat Ed Douair" },
    { id: 2634, name: "الزبيرية", nameAscii: "Zoubiria" },
  ],
  "Mostaganem": [
    { id: 2717, name: "عشعاشة", nameAscii: "Achaacha" },
    { id: 2728, name: "عين بودينار", nameAscii: "Ain-Boudinar" },
    { id: 2705, name: "عين نويسي", nameAscii: "Ain-Nouissy" },
    { id: 2721, name: "عين سيدي الشريف", nameAscii: "Ain-Sidi Cherif" },
    { id: 2707, name: "عين تادلس", nameAscii: "Ain-Tedles" },
    { id: 2713, name: "بن عبد المالك رمضان", nameAscii: "Benabdelmalek Ramdane" },
    { id: 2719, name: "بوقيراط", nameAscii: "Bouguirat" },
    { id: 2703, name: "فرناقة", nameAscii: "Fornaka" },
    { id: 2714, name: "حجاج", nameAscii: "Hadjadj" },
    { id: 2706, name: "حاسي ماماش", nameAscii: "Hassi Mameche" },
    { id: 2732, name: "الحسيان (بني ياحي", nameAscii: "Hassiane" },
    { id: 2718, name: "خضرة", nameAscii: "Khadra" },
    { id: 2711, name: "خير الدين", nameAscii: "Kheir-Eddine" },
    { id: 2723, name: "منصورة", nameAscii: "Mansourah" },
    { id: 2727, name: "مزغران", nameAscii: "Mazagran" },
    { id: 2722, name: "ماسرة", nameAscii: "Mesra" },
    { id: 2701, name: "مستغانم", nameAscii: "Mostaganem" },
    { id: 2715, name: "نكمارية", nameAscii: "Nekmaria" },
    { id: 2709, name: "وادي الخير", nameAscii: "Oued El Kheir" },
    { id: 2725, name: "أولاد بوغالم", nameAscii: "Ouled Boughalem" },
    { id: 2726, name: "أولاد مع الله", nameAscii: "Ouled-Maalah" },
    { id: 2730, name: "صفصاف", nameAscii: "Safsaf" },
    { id: 2702, name: "صيادة", nameAscii: "Sayada" },
    { id: 2712, name: "سيدي علي", nameAscii: "Sidi Ali" },
    { id: 2710, name: "سيدي بلعطار", nameAscii: "Sidi Belaattar" },
    { id: 2716, name: "سيدي لخضر", nameAscii: "Sidi-Lakhdar" },
    { id: 2720, name: "سيرات", nameAscii: "Sirat" },
    { id: 2724, name: "السوافلية", nameAscii: "Souaflia" },
    { id: 2708, name: "سور", nameAscii: "Sour" },
    { id: 2704, name: "ستيدية", nameAscii: "Stidia" },
    { id: 2729, name: "تزقايت", nameAscii: "Tazgait" },
    { id: 2731, name: "الطواهرية", nameAscii: "Touahria" },
  ],
  "M'Sila": [
    { id: 2817, name: "عين الحجل", nameAscii: "Ain El Hadjel" },
    { id: 2813, name: "عين الخضراء", nameAscii: "Ain Khadra" },
    { id: 2815, name: "بلعايبة", nameAscii: "Belaiba" },
    { id: 2845, name: "بني يلمان", nameAscii: "Beni Ilmane" },
    { id: 2812, name: "برهوم", nameAscii: "Berhoum" },
    { id: 2831, name: "بوطي السايح", nameAscii: "Bouti Sayeh" },
    { id: 2809, name: "شلال", nameAscii: "Chellal" },
    { id: 2830, name: "دهاهنة", nameAscii: "Dehahna" },
    { id: 2803, name: "حمام الضلعة", nameAscii: "Hammam Dalaa" },
    { id: 2832, name: "خطوطي سد الجير", nameAscii: "Khettouti Sed-El-Jir" },
    { id: 2801, name: "المسيلة", nameAscii: "M'sila" },
    { id: 2806, name: "المطارفة", nameAscii: "M'tarfa" },
    { id: 2802, name: "المعاضيد", nameAscii: "Maadid" },
    { id: 2829, name: "معاريف", nameAscii: "Maarif" },
    { id: 2811, name: "مقرة", nameAscii: "Magra" },
    { id: 2819, name: "ونوغة", nameAscii: "Ouanougha" },
    { id: 2814, name: "أولاد عدي لقبالة", nameAscii: "Ouled Addi Guebala" },
    { id: 2804, name: "أولاد دراج", nameAscii: "Ouled Derradj" },
    { id: 2810, name: "أولاد ماضي", nameAscii: "Ouled Madhi" },
    { id: 2828, name: "أولاد منصور", nameAscii: "Ouled Mansour" },
    { id: 2816, name: "سيدي عيسى", nameAscii: "Sidi Aissa" },
    { id: 2818, name: "سيدي هجرس", nameAscii: "Sidi Hadjeres" },
    { id: 2840, name: "السوامع", nameAscii: "Souamaa" },
    { id: 2805, name: "تارمونت", nameAscii: "Tarmount" },
  ],
  "Mascara": [
    { id: 2924, name: "عين فارس", nameAscii: "Ain Fares" },
    { id: 2918, name: "عين فكان", nameAscii: "Ain Fekan" },
    { id: 2911, name: "عين فراح", nameAscii: "Ain Ferah" },
    { id: 2925, name: "عين أفرص", nameAscii: "Ain Frass" },
    { id: 2928, name: "العلايمية", nameAscii: "Alaimia" },
    { id: 2923, name: "عوف", nameAscii: "Aouf" },
    { id: 2919, name: "بنيان", nameAscii: "Benian" },
    { id: 2937, name: "بوهني", nameAscii: "Bou Henni" },
    { id: 2902, name: "بوحنيفية", nameAscii: "Bouhanifia" },
    { id: 2943, name: "الشرفاء", nameAscii: "Chorfa" },
    { id: 2917, name: "البرج", nameAscii: "El Bordj" },
    { id: 2929, name: "القعدة", nameAscii: "El Gaada" },
    { id: 2934, name: "الغمري", nameAscii: "El Ghomri" },
    { id: 2938, name: "القطنة", nameAscii: "El Gueitena" },
    { id: 2907, name: "الحشم", nameAscii: "El Hachem" },
    { id: 2940, name: "القرط", nameAscii: "El Keurt" },
    { id: 2939, name: "المأمونية", nameAscii: "El Mamounia" },
    { id: 2921, name: "المنور", nameAscii: "El Menaouer" },
    { id: 2933, name: "فراقيق", nameAscii: "Ferraguig" },
    { id: 2913, name: "فروحة", nameAscii: "Froha" },
    { id: 2941, name: "غروس", nameAscii: "Gharrous" },
    { id: 2912, name: "غريس", nameAscii: "Ghriss" },
    { id: 2942, name: "قرجوم", nameAscii: "Guerdjoum" },
    { id: 2904, name: "حسين", nameAscii: "Hacine" },
    { id: 2920, name: "خلوية", nameAscii: "Khalouia" },
    { id: 2915, name: "ماقضة", nameAscii: "Makhda" },
    { id: 2905, name: "ماوسة", nameAscii: "Maoussa" },
    { id: 2901, name: "معسكر", nameAscii: "Mascara" },
    { id: 2914, name: "المطمور", nameAscii: "Matemore" },
    { id: 2936, name: "مقطع الدوز", nameAscii: "Mocta-Douz" },
    { id: 2931, name: "المحمدية", nameAscii: "Mohammadia" },
    { id: 2945, name: "نسمط", nameAscii: "Nesmot" },
    { id: 2927, name: "عقاز", nameAscii: "Oggaz" },
    { id: 2910, name: "وادي الأبطال", nameAscii: "Oued El Abtal" },
    { id: 2922, name: "وادي التاغية", nameAscii: "Oued Taria" },
    { id: 2944, name: "رأس عين عميروش", nameAscii: "Ras El Ain Amirouche" },
    { id: 2935, name: "سجرارة", nameAscii: "Sedjerara" },
    { id: 2947, name: "السهايلية", nameAscii: "Sehailia" },
    { id: 2946, name: "سيدي عبد الجبار", nameAscii: "Sidi Abdeldjebar" },
    { id: 2932, name: "سيدي عبد المومن", nameAscii: "Sidi Abdelmoumene" },
    { id: 2916, name: "سيدي بوسعيد", nameAscii: "Sidi Boussaid" },
    { id: 2908, name: "سيدي قادة", nameAscii: "Sidi Kada" },
    { id: 2926, name: "سيق", nameAscii: "Sig" },
    { id: 2906, name: "تيغنيف", nameAscii: "Tighennif" },
    { id: 2903, name: "تيزي", nameAscii: "Tizi" },
    { id: 2930, name: "زهانة", nameAscii: "Zahana" },
    { id: 2909, name: "زلامطة", nameAscii: "Zelamta" },
  ],
  "Ouargla": [
    { id: 3002, name: "عين البيضاء", nameAscii: "Ain Beida" },
    { id: 3021, name: "البرمة", nameAscii: "El Borma" },
    { id: 3012, name: "حاسي بن عبد الله", nameAscii: "Hassi Ben Abdellah" },
    { id: 3004, name: "حاسي مسعود", nameAscii: "Hassi Messaoud" },
    { id: 3003, name: "انقوسة", nameAscii: "N'goussa" },
    { id: 3001, name: "ورقلة", nameAscii: "Ouargla" },
    { id: 3005, name: "الرويسات", nameAscii: "Rouissat" },
    { id: 3011, name: "سيدي خويلد", nameAscii: "Sidi Khouiled" },
  ],
  "Oran": [
    { id: 3126, name: "عين البية", nameAscii: "Ain Biya" },
    { id: 3109, name: "عين الترك", nameAscii: "Ain Turk" },
    { id: 3106, name: "أرزيو", nameAscii: "Arzew" },
    { id: 3120, name: "بن فريحة", nameAscii: "Ben Freha" },
    { id: 3107, name: "بطيوة", nameAscii: "Bethioua" },
    { id: 3103, name: "بئر الجير", nameAscii: "Bir El Djir" },
    { id: 3114, name: "بوفاتيس", nameAscii: "Boufatis" },
    { id: 3116, name: "بوسفر", nameAscii: "Bousfer" },
    { id: 3124, name: "بوتليليس", nameAscii: "Boutlelis" },
    { id: 3110, name: "العنصر", nameAscii: "El Ancor" },
    { id: 3118, name: "البراية", nameAscii: "El Braya" },
    { id: 3117, name: "الكرمة", nameAscii: "El Kerma" },
    { id: 3105, name: "السانية", nameAscii: "Es Senia" },
    { id: 3102, name: "قديل", nameAscii: "Gdyel" },
    { id: 3119, name: "حاسي بن عقبة", nameAscii: "Hassi Ben Okba" },
    { id: 3104, name: "حاسي بونيف", nameAscii: "Hassi Bounif" },
    { id: 3121, name: "حاسي مفسوخ", nameAscii: "Hassi Mefsoukh" },
    { id: 3108, name: "مرسى الحجاج", nameAscii: "Marsat El Hadjadj" },
    { id: 3115, name: "المرسى الكبير", nameAscii: "Mers El Kebir" },
    { id: 3123, name: "مسرغين", nameAscii: "Messerghin" },
    { id: 3101, name: "وهران", nameAscii: "Oran" },
    { id: 3111, name: "وادي تليلات", nameAscii: "Oued Tlelat" },
    { id: 3122, name: "سيدي بن يبقى", nameAscii: "Sidi Ben Yebka" },
    { id: 3113, name: "سيدي الشحمي", nameAscii: "Sidi Chami" },
    { id: 3112, name: "طفراوي", nameAscii: "Tafraoui" },
  ],
  "El Bayadh": [
    { id: 3206, name: "بوعلام", nameAscii: "Boualem" },
    { id: 3210, name: "بوقطب", nameAscii: "Bougtoub" },
    { id: 3204, name: "بريزينة", nameAscii: "Brezina" },
    { id: 3217, name: "الشقيق", nameAscii: "Cheguig" },
    { id: 3201, name: "البيض", nameAscii: "El Bayadh" },
    { id: 3211, name: "الخيثر", nameAscii: "El Kheiter" },
    { id: 3205, name: "الغاسول", nameAscii: "Ghassoul" },
    { id: 3212, name: "الكاف الأحمر", nameAscii: "Kef El Ahmar" },
    { id: 3215, name: "كراكدة", nameAscii: "Krakda" },
    { id: 3202, name: "رقاصة", nameAscii: "Rogassa" },
    { id: 3218, name: "سيدي عامر", nameAscii: "Sidi Ameur" },
    { id: 3221, name: "سيدي سليمان", nameAscii: "Sidi Slimane" },
    { id: 3222, name: "سيدي طيفور", nameAscii: "Sidi Tiffour" },
    { id: 3203, name: "ستيتن", nameAscii: "Stitten" },
    { id: 3220, name: "توسمولين", nameAscii: "Tousmouline" },
  ],
  "Illizi": [
    { id: 3304, name: "برج عمر إدريس", nameAscii: "Bordj Omar Driss" },
    { id: 3303, name: "دبداب", nameAscii: "Debdeb" },
    { id: 3301, name: "إيليزي", nameAscii: "Illizi" },
    { id: 3306, name: "إن أمناس", nameAscii: "In Amenas" },
  ],
  "Bordj Bou Arréridj": [
    { id: 3408, name: "عين تاغروت", nameAscii: "Ain Taghrout" },
    { id: 3430, name: "عين تسرة", nameAscii: "Ain Tesra" },
    { id: 3412, name: "بليمور", nameAscii: "Belimour" },
    { id: 3406, name: "بن داود", nameAscii: "Ben Daoud" },
    { id: 3431, name: "بئر قاصد علي", nameAscii: "Bir Kasdali" },
    { id: 3401, name: "برج بوعريرج", nameAscii: "Bordj Bou Arreridj" },
    { id: 3409, name: "برج الغدير", nameAscii: "Bordj Ghedir" },
    { id: 3403, name: "برج زمورة", nameAscii: "Bordj Zemmoura" },
    { id: 3425, name: "القلة", nameAscii: "Colla" },
    { id: 3415, name: "جعافرة", nameAscii: "Djaafra" },
    { id: 3407, name: "الياشير", nameAscii: "El Achir" },
    { id: 3428, name: "العناصر", nameAscii: "El Annasseur" },
    { id: 3407, name: "العش", nameAscii: "El Euch" },
    { id: 3405, name: "المهير", nameAscii: "El M'hir" },
    { id: 3416, name: "الماين", nameAscii: "El Main" },
    { id: 3411, name: "الحمادية", nameAscii: "Elhammadia" },
    { id: 3432, name: "غيلاسة", nameAscii: "Ghailasa" },
    { id: 3434, name: "حرازة", nameAscii: "Haraza" },
    { id: 3419, name: "حسناوة", nameAscii: "Hasnaoua" },
    { id: 3420, name: "خليل", nameAscii: "Khelil" },
    { id: 3422, name: "القصور", nameAscii: "Ksour" },
    { id: 3404, name: "المنصورة", nameAscii: "Mansoura" },
    { id: 3413, name: "مجانة", nameAscii: "Medjana" },
    { id: 3417, name: "أولاد أبراهم", nameAscii: "Ouled Brahem" },
    { id: 3418, name: "أولاد دحمان", nameAscii: "Ouled Dahmane" },
    { id: 3423, name: "أولاد سيدي ابراهيم", nameAscii: "Ouled Sidi-Brahim" },
    { id: 3433, name: "الرابطة", nameAscii: "Rabta" },
    { id: 3402, name: "رأس الوادي", nameAscii: "Ras El Oued" },
    { id: 3410, name: "سيدي أمبارك", nameAscii: "Sidi-Embarek" },
    { id: 3421, name: "تقلعيت", nameAscii: "Taglait" },
    { id: 3429, name: "تسامرت", nameAscii: "Tassamert" },
    { id: 3424, name: "تفرق", nameAscii: "Tefreg" },
    { id: 3414, name: "ثنية النصر", nameAscii: "Teniet En Nasr" },
    { id: 3426, name: "تيكستار", nameAscii: "Tixter" },
  ],
  "Boumerdès": [
    { id: 3503, name: "أعفير", nameAscii: "Afir" },
    { id: 3524, name: "عمال", nameAscii: "Ammal" },
    { id: 3505, name: "بغلية", nameAscii: "Baghlia" },
    { id: 3522, name: "بن شود", nameAscii: "Ben Choud" },
    { id: 3525, name: "بني عمران", nameAscii: "Beni Amrane" },
    { id: 3504, name: "برج منايل", nameAscii: "Bordj Menaiel" },
    { id: 3502, name: "بودواو", nameAscii: "Boudouaou" },
    { id: 3527, name: "بودواو البحري", nameAscii: "Boudouaou El Bahri" },
    { id: 3501, name: "بومرداس", nameAscii: "Boumerdes" },
    { id: 3519, name: "بوزقزة قدارة", nameAscii: "Bouzegza Keddara" },
    { id: 3513, name: "شعبة العامر", nameAscii: "Chabet El Ameur" },
    { id: 3516, name: "قورصو", nameAscii: "Corso" },
    { id: 3523, name: "دلس", nameAscii: "Dellys" },
    { id: 3508, name: "جنات", nameAscii: "Djinet" },
    { id: 3532, name: "الخروبة", nameAscii: "El Kharrouba" },
    { id: 3530, name: "حمادي", nameAscii: "Hammedi" },
    { id: 3509, name: "يسر", nameAscii: "Isser" },
    { id: 3531, name: "خميس الخشنة", nameAscii: "Khemis El Khechna" },
    { id: 3518, name: "الاربعطاش", nameAscii: "Larbatache" },
    { id: 3529, name: "لقاطة", nameAscii: "Leghata" },
    { id: 3507, name: "الناصرية", nameAscii: "Naciria" },
    { id: 3521, name: "أولاد عيسى", nameAscii: "Ouled Aissa" },
    { id: 3528, name: "أولاد هداج", nameAscii: "Ouled Hedadj" },
    { id: 3517, name: "أولاد موسى", nameAscii: "Ouled Moussa" },
    { id: 3511, name: "سي مصطفى", nameAscii: "Si Mustapha" },
    { id: 3506, name: "سيدي داود", nameAscii: "Sidi Daoud" },
    { id: 3526, name: "سوق الحد", nameAscii: "Souk El Had" },
    { id: 3520, name: "تاورقة", nameAscii: "Taourga" },
    { id: 3514, name: "الثنية", nameAscii: "Thenia" },
    { id: 3512, name: "تيجلابين", nameAscii: "Tidjelabine" },
    { id: 3515, name: "تيمزريت", nameAscii: "Timezrit" },
    { id: 3510, name: "زموري", nameAscii: "Zemmouri" },
  ],
  "El Tarf": [
    { id: 3606, name: "عين العسل", nameAscii: "Ain El Assel" },
    { id: 3621, name: "عين الكرمة", nameAscii: "Ain Kerma" },
    { id: 3617, name: "عصفور", nameAscii: "Asfour" },
    { id: 3603, name: "بن مهيدي", nameAscii: "Ben M Hidi" },
    { id: 3610, name: "بريحان", nameAscii: "Berrihane" },
    { id: 3616, name: "البسباس", nameAscii: "Besbes" },
    { id: 3604, name: "بوقوس", nameAscii: "Bougous" },
    { id: 3602, name: "بوحجار", nameAscii: "Bouhadjar" },
    { id: 3608, name: "بوثلجة", nameAscii: "Bouteldja" },
    { id: 3615, name: "شبيطة مختار", nameAscii: "Chebaita Mokhtar" },
    { id: 3612, name: "الشافية", nameAscii: "Chefia" },
    { id: 3614, name: "شحاني", nameAscii: "Chihani" },
    { id: 3613, name: "الذرعـان", nameAscii: "Drean" },
    { id: 3618, name: "الشط", nameAscii: "Echatt" },
    { id: 3607, name: "العيون", nameAscii: "El Aioun" },
    { id: 3605, name: "القالة", nameAscii: "El Kala" },
    { id: 3601, name: "الطارف", nameAscii: "El Tarf" },
    { id: 3623, name: "حمام بني صالح", nameAscii: "Hammam Beni Salah" },
    { id: 3611, name: "بحيرة الطيور", nameAscii: "Lac Des Oiseaux" },
    { id: 3622, name: "وادي الزيتون", nameAscii: "Oued Zitoun" },
    { id: 3624, name: "رمل السوق", nameAscii: "Raml Souk" },
    { id: 3609, name: "السوارخ", nameAscii: "Souarekh" },
    { id: 3619, name: "زريزر", nameAscii: "Zerizer" },
    { id: 3620, name: "الزيتونة", nameAscii: "Zitouna" },
  ],
  "Tindouf": [
    { id: 3702, name: "أم العسل", nameAscii: "Oum El Assel" },
    { id: 3701, name: "تندوف", nameAscii: "Tindouf" },
  ],
  "Tissemsilt": [
    { id: 3813, name: "عماري", nameAscii: "Ammari" },
    { id: 3805, name: "بني شعيب", nameAscii: "Beni Chaib" },
    { id: 3822, name: "بني لحسن", nameAscii: "Beni Lahcene" },
    { id: 3802, name: "برج بونعامة", nameAscii: "Bordj Bounaama" },
    { id: 3809, name: "برج الأمير عبد القادر", nameAscii: "Bordj El Emir Abdelkader" },
    { id: 3821, name: "بوقائد", nameAscii: "Boucaid" },
    { id: 3811, name: "خميستي", nameAscii: "Khemisti" },
    { id: 3816, name: "الأربعاء", nameAscii: "Larbaa" },
    { id: 3806, name: "لرجام", nameAscii: "Lardjem" },
    { id: 3810, name: "العيون", nameAscii: "Layoune" },
    { id: 3804, name: "الأزهرية", nameAscii: "Lazharia" },
    { id: 3817, name: "المعاصم", nameAscii: "Maacem" },
    { id: 3807, name: "الملعب", nameAscii: "Melaab" },
    { id: 3812, name: "أولاد بسام", nameAscii: "Ouled Bessam" },
    { id: 3818, name: "سيدي عابد", nameAscii: "Sidi Abed" },
    { id: 3815, name: "سيدي بوتوشنت", nameAscii: "Sidi Boutouchent" },
    { id: 3808, name: "سيدي العنتري", nameAscii: "Sidi Lantri" },
    { id: 3820, name: "سيدي سليمان", nameAscii: "Sidi Slimane" },
    { id: 3819, name: "تملاحت", nameAscii: "Tamellahet" },
    { id: 3803, name: "ثنية الاحد", nameAscii: "Theniet El Had" },
    { id: 3801, name: "تيسمسيلت", nameAscii: "Tissemsilt" },
    { id: 3814, name: "اليوسفية", nameAscii: "Youssoufia" },
  ],
  "El Oued": [
    { id: 3904, name: "البياضة", nameAscii: "Bayadha" },
    { id: 3919, name: "بن قشة", nameAscii: "Ben Guecha" },
    { id: 3911, name: "الدبيلة", nameAscii: "Debila" },
    { id: 3915, name: "دوار الماء", nameAscii: "Douar El Maa" },
    { id: 3925, name: "العقلة", nameAscii: "El Ogla" },
    { id: 3901, name: "الوادي", nameAscii: "El-Oued" },
    { id: 3906, name: "قمار", nameAscii: "Guemar" },
    { id: 3909, name: "الحمراية", nameAscii: "Hamraia" },
    { id: 3912, name: "حساني عبد الكريم", nameAscii: "Hassani Abdelkrim" },
    { id: 3913, name: "حاسي خليفة", nameAscii: "Hassi Khalifa" },
    { id: 3907, name: "كوينين", nameAscii: "Kouinine" },
    { id: 3918, name: "المقرن", nameAscii: "Magrane" },
    { id: 3926, name: "اميه وانسة", nameAscii: "Mih Ouansa" },
    { id: 3905, name: "النخلة", nameAscii: "Nakhla" },
    { id: 3903, name: "وادي العلندة", nameAscii: "Oued El Alenda" },
    { id: 3920, name: "ورماس", nameAscii: "Ourmes" },
    { id: 3908, name: "الرقيبة", nameAscii: "Reguiba" },
    { id: 3902, name: "الرباح", nameAscii: "Robbah" },
    { id: 3916, name: "سيدي عون", nameAscii: "Sidi Aoun" },
    { id: 3910, name: "تغزوت", nameAscii: "Taghzout" },
    { id: 3914, name: "الطالب العربي", nameAscii: "Taleb Larbi" },
    { id: 3917, name: "الطريفاوي", nameAscii: "Trifaoui" },
  ],
  "Khenchela": [
    { id: 4006, name: "عين الطويلة", nameAscii: "Ain Touila" },
    { id: 4013, name: "بابار", nameAscii: "Babar" },
    { id: 4004, name: "بغاي", nameAscii: "Baghai" },
    { id: 4008, name: "بوحمامة", nameAscii: "Bouhmama" },
    { id: 4011, name: "ششار", nameAscii: "Chechar" },
    { id: 4021, name: "شلية", nameAscii: "Chelia" },
    { id: 4012, name: "جلال", nameAscii: "Djellal" },
    { id: 4005, name: "الحامة", nameAscii: "El Hamma" },
    { id: 4017, name: "المحمل", nameAscii: "El Mahmal" },
    { id: 4009, name: "الولجة", nameAscii: "El Oueldja" },
    { id: 4015, name: "انسيغة", nameAscii: "Ensigha" },
    { id: 4003, name: "قايس", nameAscii: "Kais" },
    { id: 4001, name: "خنشلة", nameAscii: "Khenchela" },
    { id: 4020, name: "خيران", nameAscii: "Khirane" },
    { id: 4018, name: "مصارة", nameAscii: "M'sara" },
    { id: 4002, name: "متوسة", nameAscii: "M'toussa" },
    { id: 4016, name: "أولاد رشاش", nameAscii: "Ouled Rechache" },
    { id: 4010, name: "الرميلة", nameAscii: "Remila" },
    { id: 4014, name: "طامزة", nameAscii: "Tamza" },
    { id: 4007, name: "تاوزيانت", nameAscii: "Taouzianat" },
    { id: 4019, name: "يابوس", nameAscii: "Yabous" },
  ],
  "Souk Ahras": [
    { id: 4118, name: "عين سلطان", nameAscii: "Ain Soltane" },
    { id: 4117, name: "عين الزانة", nameAscii: "Ain Zana" },
    { id: 4114, name: "بئر بوحوش", nameAscii: "Bir Bouhouche" },
    { id: 4109, name: "الدريعة", nameAscii: "Drea" },
    { id: 4110, name: "الحدادة", nameAscii: "Haddada" },
    { id: 4103, name: "الحنانشة", nameAscii: "Hanencha" },
    { id: 4111, name: "الخضارة", nameAscii: "Khedara" },
    { id: 4123, name: "خميسة", nameAscii: "Khemissa" },
    { id: 4115, name: "مداوروش", nameAscii: "M'daourouche" },
    { id: 4104, name: "المشروحة", nameAscii: "Machroha" },
    { id: 4112, name: "المراهنة", nameAscii: "Merahna" },
    { id: 4118, name: "وادي الكبريت", nameAscii: "Oued Kebrit" },
    { id: 4119, name: "ويلان", nameAscii: "Ouillen" },
    { id: 4105, name: "أولاد إدريس", nameAscii: "Ouled Driss" },
    { id: 4113, name: "أولاد مومن", nameAscii: "Ouled Moumen" },
    { id: 4116, name: "أم العظايم", nameAscii: "Oum El Adhaim" },
    { id: 4122, name: "الراقوبة", nameAscii: "Ragouba" },
    { id: 4121, name: "سافل الويدان", nameAscii: "Safel El Ouiden" },
    { id: 4102, name: "سدراتة", nameAscii: "Sedrata" },
    { id: 4118, name: "سيدي فرج", nameAscii: "Sidi Fredj" },
    { id: 4101, name: "سوق أهراس", nameAscii: "Souk Ahras" },
    { id: 4108, name: "تاورة", nameAscii: "Taoura" },
    { id: 4125, name: "ترقالت", nameAscii: "Terraguelt" },
    { id: 4106, name: "تيفاش", nameAscii: "Tiffech" },
    { id: 4104, name: "الزعرورية", nameAscii: "Zaarouria" },
    { id: 4126, name: "الزوابي", nameAscii: "Zouabi" },
  ],
  "Tipaza": [
    { id: 4210, name: "أغبال", nameAscii: "Aghbal" },
    { id: 4227, name: "أحمر العين", nameAscii: "Ahmer El Ain" },
    { id: 4217, name: "عين تاقورايت", nameAscii: "Ain Tagourait" },
    { id: 4236, name: "الحطاطبة", nameAscii: "Attatba" },
    { id: 4241, name: "بني ميلك", nameAscii: "Beni Mileuk" },
    { id: 4209, name: "بوهارون", nameAscii: "Bou Haroun" },
    { id: 4226, name: "بواسماعيل", nameAscii: "Bou Ismail" },
    { id: 4205, name: "بورقيقة", nameAscii: "Bourkika" },
    { id: 4216, name: "الشعيبة", nameAscii: "Chaiba" },
    { id: 4222, name: "شرشال", nameAscii: "Cherchell" },
    { id: 4223, name: "الداموس", nameAscii: "Damous" },
    { id: 4204, name: "دواودة", nameAscii: "Douaouda" },
    { id: 4225, name: "فوكة", nameAscii: "Fouka" },
    { id: 4202, name: "قوراية", nameAscii: "Gouraya" },
    { id: 4212, name: "حجوط", nameAscii: "Hadjout" },
    { id: 4242, name: "حجرة النص", nameAscii: "Hadjret Ennous" },
    { id: 4206, name: "خميستي", nameAscii: "Khemisti" },
    { id: 4235, name: "القليعة", nameAscii: "Kolea" },
    { id: 4203, name: "الأرهاط", nameAscii: "Larhat" },
    { id: 4202, name: "مناصر", nameAscii: "Menaceur" },
    { id: 4224, name: "مراد", nameAscii: "Merad" },
    { id: 4233, name: "مسلمون", nameAscii: "Messelmoun" },
    { id: 4215, name: "الناظور", nameAscii: "Nador" },
    { id: 4232, name: "سيدي غيلاس", nameAscii: "Sidi Ghiles" },
    { id: 4234, name: "سيدي راشد", nameAscii: "Sidi Rached" },
    { id: 4240, name: "سيدي سميان", nameAscii: "Sidi Semiane" },
    { id: 4213, name: "سيدي عامر", nameAscii: "Sidi-Amar" },
    { id: 4201, name: "تيبازة", nameAscii: "Tipaza" },
  ],
  "Mila": [
    { id: 4311, name: "أحمد راشدي", nameAscii: "Ahmed Rachedi" },
    { id: 4319, name: "عين البيضاء أحريش", nameAscii: "Ain Beida Harriche" },
    { id: 4305, name: "عين الملوك", nameAscii: "Ain Mellouk" },
    { id: 4325, name: "عين التين", nameAscii: "Ain Tine" },
    { id: 4322, name: "اعميرة اراس", nameAscii: "Amira Arres" },
    { id: 4309, name: "بن يحي عبد الرحمن", nameAscii: "Benyahia Abderrahmane" },
    { id: 4314, name: "بوحاتم", nameAscii: "Bouhatem" },
    { id: 4303, name: "شلغوم العيد", nameAscii: "Chelghoum Laid" },
    { id: 4332, name: "الشيقارة", nameAscii: "Chigara" },
    { id: 4320, name: "دراحي بوصلاح", nameAscii: "Derrahi Bousselah" },
    { id: 4315, name: "العياضي برباس", nameAscii: "El Ayadi Barbes" },
    { id: 4326, name: "مشيرة", nameAscii: "El Mechira" },
    { id: 4302, name: "فرجيوة", nameAscii: "Ferdjioua" },
    { id: 4317, name: "القرارم قوقة", nameAscii: "Grarem Gouga" },
    { id: 4324, name: "حمالة", nameAscii: "Hamala" },
    { id: 4301, name: "ميلة", nameAscii: "Mila" },
    { id: 4321, name: "مينار زارزة", nameAscii: "Minar Zarza" },
    { id: 4304, name: "وادي العثمانية", nameAscii: "Oued Athmenia" },
    { id: 4310, name: "وادي النجاء", nameAscii: "Oued Endja" },
    { id: 4307, name: "وادي سقان", nameAscii: "Oued Seguen" },
    { id: 4312, name: "أولاد اخلوف", nameAscii: "Ouled Khalouf" },
    { id: 4315, name: "الرواشد", nameAscii: "Rouached" },
    { id: 4327, name: "سيدي خليفة", nameAscii: "Sidi Khelifa" },
    { id: 4318, name: "سيدي مروان", nameAscii: "Sidi Merouane" },
    { id: 4308, name: "تاجنانت", nameAscii: "Tadjenanet" },
    { id: 4319, name: "تسدان حدادة", nameAscii: "Tassadane Haddada" },
    { id: 4308, name: "تسالة لمطاعي", nameAscii: "Tassala Lematai" },
    { id: 4306, name: "التلاغمة", nameAscii: "Teleghma" },
    { id: 4323, name: "ترعي باينان", nameAscii: "Terrai Bainen" },
    { id: 4313, name: "تيبرقنت", nameAscii: "Tiberguent" },
    { id: 4305, name: "يحي بني قشة", nameAscii: "Yahia Beniguecha" },
    { id: 4328, name: "زغاية", nameAscii: "Zeghaia" },
  ],
  "Aïn Defla": [
    { id: 4426, name: "عين البنيان", nameAscii: "Ain-Benian" },
    { id: 4433, name: "عين بويحيى", nameAscii: "Ain-Bouyahia" },
    { id: 4401, name: "عين الدفلى", nameAscii: "Ain-Defla" },
    { id: 4414, name: "عين الاشياخ", nameAscii: "Ain-Lechiakh" },
    { id: 4420, name: "عين السلطان", nameAscii: "Ain-Soltane" },
    { id: 4423, name: "عين التركي", nameAscii: "Ain-Torki" },
    { id: 4406, name: "عريب", nameAscii: "Arib" },
    { id: 4431, name: "بطحية", nameAscii: "Bathia" },
    { id: 4436, name: "بلعاص", nameAscii: "Belaas" },
    { id: 4425, name: "بن علال", nameAscii: "Ben Allal" },
    { id: 4410, name: "بئر ولد خليفة", nameAscii: "Bir-Ould-Khelifa" },
    { id: 4428, name: "بربوش", nameAscii: "Birbouche" },
    { id: 4422, name: "برج الأمير خالد", nameAscii: "Bordj-Emir-Khaled" },
    { id: 4403, name: "بومدفع", nameAscii: "Boumedfaa" },
    { id: 4409, name: "بوراشد", nameAscii: "Bourached" },
    { id: 4407, name: "جليدة", nameAscii: "Djelida" },
    { id: 4429, name: "جمعة أولاد الشيخ", nameAscii: "Djemaa Ouled Cheikh" },
    { id: 4405, name: "جندل", nameAscii: "Djendel" },
    { id: 4411, name: "العبادية", nameAscii: "El-Abadia" },
    { id: 4408, name: "العامرة", nameAscii: "El-Amra" },
    { id: 4410, name: "العطاف", nameAscii: "El-Attaf" },
    { id: 4423, name: "الماين", nameAscii: "El-Maine" },
    { id: 4405, name: "حمام ريغة", nameAscii: "Hammam-Righa" },
    { id: 4418, name: "الحسانية", nameAscii: "Hassania" },
    { id: 4427, name: "الحسينية", nameAscii: "Hoceinia" },
    { id: 4404, name: "خميس مليانة", nameAscii: "Khemis-Miliana" },
    { id: 4430, name: "المخاطرية", nameAscii: "Mekhatria" },
    { id: 4402, name: "مليانة", nameAscii: "Miliana" },
    { id: 4413, name: "وادي الشرفاء", nameAscii: "Oued Chorfa" },
    { id: 4415, name: "واد الجمعة", nameAscii: "Oued Djemaa" },
    { id: 4416, name: "الروينة", nameAscii: "Rouina" },
    { id: 4424, name: "سيدي الأخضر", nameAscii: "Sidi-Lakhdar" },
    { id: 4432, name: "تاشتة زقاغة", nameAscii: "Tacheta Zegagha" },
    { id: 4421, name: "طارق بن زياد", nameAscii: "Tarik-Ibn-Ziad" },
    { id: 4435, name: "تبركانين", nameAscii: "Tiberkanine" },
    { id: 4417, name: "زدين", nameAscii: "Zeddine" },
  ],
  "Naâma": [
    { id: 4509, name: "عين بن خليل", nameAscii: "Ain Ben Khelil" },
    { id: 4503, name: "عين الصفراء", nameAscii: "Ain Sefra" },
    { id: 4504, name: "عسلة", nameAscii: "Asla" },
    { id: 4504, name: "جنين بورزق", nameAscii: "Djenienne Bourezg" },
    { id: 4512, name: "البيوض", nameAscii: "El Biodh" },
    { id: 4511, name: "القصدير", nameAscii: "Kasdir" },
    { id: 4510, name: "مكمن بن عمار", nameAscii: "Makmen Ben Amar" },
    { id: 4502, name: "المشرية", nameAscii: "Mecheria" },
    { id: 4506, name: "مغرار", nameAscii: "Moghrar" },
    { id: 4501, name: "النعامة", nameAscii: "Naama" },
    { id: 4503, name: "سفيسيفة", nameAscii: "Sfissifa" },
    { id: 4504, name: "تيوت", nameAscii: "Tiout" },
  ],
  "Aïn Témouchent": [
    { id: 4607, name: "أغلال", nameAscii: "Aghlal" },
    { id: 4609, name: "عين الأربعاء", nameAscii: "Ain El Arbaa" },
    { id: 4622, name: "عين الكيحل", nameAscii: "Ain Kihal" },
    { id: 4601, name: "عين تموشنت", nameAscii: "Ain Temouchent" },
    { id: 4618, name: "عين الطلبة", nameAscii: "Ain Tolba" },
    { id: 4613, name: "عقب الليل", nameAscii: "Aoubellil" },
    { id: 4623, name: "بني صاف", nameAscii: "Beni Saf" },
    { id: 4605, name: "بوزجار", nameAscii: "Bouzedjar" },
    { id: 4605, name: "شعبة اللحم", nameAscii: "Chaabat El Ham" },
    { id: 4611, name: "شنتوف", nameAscii: "Chentouf" },
    { id: 4606, name: "العامرية", nameAscii: "El Amria" },
    { id: 4607, name: "المالح", nameAscii: "El Maleh" },
    { id: 4628, name: "المساعيد", nameAscii: "El Messaid" },
    { id: 4604, name: "حمام بوحجر", nameAscii: "Hammam Bou Hadjar" },
    { id: 4621, name: "الحساسنة", nameAscii: "Hassasna" },
    { id: 4620, name: "حاسي الغلة", nameAscii: "Hassi El Ghella" },
    { id: 4606, name: "وادي برقش", nameAscii: "Oued Berkeche" },
    { id: 4616, name: "وادي الصباح", nameAscii: "Oued Sebbah" },
    { id: 4617, name: "أولاد بوجمعة", nameAscii: "Ouled Boudjemaa" },
    { id: 4622, name: "أولاد الكيحل", nameAscii: "Ouled Kihal" },
    { id: 4625, name: "ولهاصة الغرابة", nameAscii: "Oulhaca El Gheraba" },
    { id: 4612, name: "سيدي بن عدة", nameAscii: "Sidi Ben Adda" },
    { id: 4615, name: "سيدي بومدين", nameAscii: "Sidi Boumediene" },
    { id: 4605, name: "سيدي ورياش", nameAscii: "Sidi Ouriache" },
    { id: 4624, name: "سيدي صافي", nameAscii: "Sidi Safi" },
    { id: 4610, name: "تامزورة", nameAscii: "Tamzoura" },
    { id: 4608, name: "تارقة", nameAscii: "Terga" },
  ],
  "Ghardaïa": [
    { id: 4704, name: "بريان", nameAscii: "Berriane" },
    { id: 4710, name: "بونورة", nameAscii: "Bounoura" },
    { id: 4707, name: "ضاية بن ضحوة", nameAscii: "Dhayet Bendhahoua" },
    { id: 4712, name: "العطف", nameAscii: "El Atteuf" },
    { id: 4702, name: "القرارة", nameAscii: "El Guerrara" },
    { id: 4701, name: "غرداية", nameAscii: "Ghardaia" },
    { id: 4713, name: "المنصورة", nameAscii: "Mansoura" },
    { id: 4705, name: "متليلي", nameAscii: "Metlili" },
    { id: 4709, name: "سبسب", nameAscii: "Sebseb" },
    { id: 4708, name: "زلفانة", nameAscii: "Zelfana" },
  ],
  "Relizane": [
    { id: 4824, name: "عين الرحمة", nameAscii: "Ain Rahma" },
    { id: 4815, name: "عين طارق", nameAscii: "Ain-Tarek" },
    { id: 4811, name: "عمي موسى", nameAscii: "Ammi Moussa" },
    { id: 4803, name: "بلعسل بوزقزة", nameAscii: "Belaassel Bouzagza" },
    { id: 4835, name: "بن داود", nameAscii: "Bendaoud" },
    { id: 4813, name: "بني درقن", nameAscii: "Beni Dergoun" },
    { id: 4830, name: "بني زنطيس", nameAscii: "Beni Zentis" },
    { id: 4832, name: "دار بن عبد الله", nameAscii: "Dar Ben Abdelah" },
    { id: 4814, name: "جديوية", nameAscii: "Djidiouia" },
    { id: 4807, name: "الحمادنة", nameAscii: "El H'madna" },
    { id: 4804, name: "الحاسي", nameAscii: "El Hassi" },
    { id: 4836, name: "الولجة", nameAscii: "El Ouldja" },
    { id: 4816, name: "القطار", nameAscii: "El-Guettar" },
    { id: 4817, name: "المطمر", nameAscii: "El-Matmar" },
    { id: 4808, name: "حد الشكالة", nameAscii: "Had Echkalla" },
    { id: 4816, name: "حمري", nameAscii: "Hamri" },
    { id: 4823, name: "القلعة", nameAscii: "Kalaa" },
    { id: 4829, name: "لحلاف", nameAscii: "Lahlef" },
    { id: 4822, name: "مازونة", nameAscii: "Mazouna" },
    { id: 4819, name: "مديونة", nameAscii: "Mediouna" },
    { id: 4828, name: "منداس", nameAscii: "Mendes" },
    { id: 4837, name: "مرجة سيدي عابد", nameAscii: "Merdja Sidi Abed" },
    { id: 4821, name: "واريزان", nameAscii: "Ouarizane" },
    { id: 4826, name: "وادي الجمعة", nameAscii: "Oued El Djemaa" },
    { id: 4820, name: "وادي السلام", nameAscii: "Oued Essalem" },
    { id: 4802, name: "وادي رهيو", nameAscii: "Oued-Rhiou" },
    { id: 4813, name: "أولاد يعيش", nameAscii: "Ouled Aiche" },
    { id: 4838, name: "أولاد سيدي الميهوب", nameAscii: "Ouled Sidi Mihoub" },
    { id: 4827, name: "الرمكة", nameAscii: "Ramka" },
    { id: 4801, name: "غليزان", nameAscii: "Relizane" },
    { id: 4810, name: "سيدي خطاب", nameAscii: "Sidi Khettab" },
    { id: 4806, name: "سيدي لزرق", nameAscii: "Sidi Lazreg" },
    { id: 4808, name: "سيدي أمحمد بن علي", nameAscii: "Sidi M'hamed Benali" },
    { id: 4824, name: "سيدي امحمد بن عودة", nameAscii: "Sidi M'hamed Benaouda" },
    { id: 4804, name: "سيدي سعادة", nameAscii: "Sidi Saada" },
    { id: 4831, name: "سوق الحد", nameAscii: "Souk El Had" },
    { id: 4825, name: "يلل", nameAscii: "Yellel" },
    { id: 4812, name: "زمورة", nameAscii: "Zemmoura" },
  ],
  "El M'Ghair": [
    { id: 123, name: "أوقروت", nameAscii: "Aougrout" },
    { id: 103, name: "شروين", nameAscii: "Charouine" },
    { id: 117, name: "دلدول", nameAscii: "Deldoul" },
    { id: 107, name: "قصر قدور", nameAscii: "Ksar Kaddour" },
    { id: 120, name: "المطارفة", nameAscii: "Metarfa" },
    { id: 127, name: "أولاد عيسى", nameAscii: "Ouled Aissa" },
    { id: 110, name: "أولاد السعيد", nameAscii: "Ouled Said" },
    { id: 124, name: "طالمين", nameAscii: "Talmine" },
    { id: 109, name: "تيميمون", nameAscii: "Timimoun" },
    { id: 116, name: "تنركوك", nameAscii: "Tinerkouk" },
  ],
  "El Meniaa": [
    { id: 125, name: "برج باجي مختار", nameAscii: "Bordj Badji Mokhtar" },
    { id: 128, name: "تيمياوين", nameAscii: "Timiaouine" },
  ],
  "Ouled Djellal": [
    { id: 707, name: "بسباس", nameAscii: "Besbes" },
    { id: 709, name: "الدوسن", nameAscii: "Doucen" },
    { id: 705, name: "أولاد جلال", nameAscii: "Ouled Djellal" },
    { id: 515, name: "رأس الميعاد", nameAscii: "Ras El Miad" },
    { id: 708, name: "سيدي خالد", nameAscii: "Sidi Khaled" },
  ],
  "Bordj Baji Mokhtar": [
    { id: 807, name: "بني عباس", nameAscii: "Beni-Abbes" },
    { id: 808, name: "بن يخلف", nameAscii: "Beni-Ikhlef" },
    { id: 814, name: "الواتة", nameAscii: "El Ouata" },
    { id: 811, name: "إقلي", nameAscii: "Igli" },
    { id: 818, name: "كرزاز", nameAscii: "Kerzaz" },
    { id: 819, name: "القصابي", nameAscii: "Ksabi" },
    { id: 803, name: "أولاد خضير", nameAscii: "Ouled-Khodeir" },
    { id: 820, name: "تامترت", nameAscii: "Tamtert" },
    { id: 805, name: "تيمودي", nameAscii: "Timoudi" },
  ],
  "Béni Abbès": [
    { id: 1108, name: "عين صالح", nameAscii: "Ain Salah" },
    { id: 1110, name: "فقارة الزوى", nameAscii: "Foggaret Ezzoua" },
    { id: 1103, name: "إينغر", nameAscii: "Inghar" },
  ],
  "Timimoun": [
    { id: 1104, name: "عين قزام", nameAscii: "Ain Guezzam" },
    { id: 1107, name: "تين زواتين", nameAscii: "Tin Zouatine" },
  ],
  "Touggourt": [
    { id: 3017, name: "بن ناصر", nameAscii: "Benaceur" },
    { id: 5507, name: "بلدة اعمر", nameAscii: "Blidet Amor" },
    { id: 3020, name: "العالية", nameAscii: "El Alia" },
    { id: 3014, name: "الحجيرة", nameAscii: "El-Hadjira" },
    { id: 3018, name: "المنقر", nameAscii: "M'naguer" },
    { id: 3019, name: "المقارين", nameAscii: "Megarine" },
    { id: 3008, name: "النزلة", nameAscii: "Nezla" },
    { id: 3015, name: "الطيبات", nameAscii: "Taibet" },
    { id: 3007, name: "تبسبست", nameAscii: "Tebesbest" },
    { id: 3016, name: "تماسين", nameAscii: "Temacine" },
    { id: 3013, name: "تقرت", nameAscii: "Touggourt" },
    { id: 3009, name: "الزاوية العابدية", nameAscii: "Zaouia El Abidia" },
  ],
  "Djanet": [
    { id: 5601, name: "برج الحواس", nameAscii: "Bordj El Haouass" },
    { id: 3302, name: "جانت", nameAscii: "Djanet" },
  ],
  "In Salah": [
    { id: 3928, name: "جامعة", nameAscii: "Djamaa" },
    { id: 3927, name: "المغير", nameAscii: "El-M'ghaier" },
    { id: 3922, name: "المرارة", nameAscii: "M'rara" },
    { id: 3929, name: "أم الطيور", nameAscii: "Oum Touyour" },
    { id: 3930, name: "سيدي عمران", nameAscii: "Sidi Amrane" },
    { id: 3923, name: "سيدي خليل", nameAscii: "Sidi Khelil" },
    { id: 3921, name: "سطيل", nameAscii: "Still" },
    { id: 3924, name: "تندلة", nameAscii: "Tenedla" },
  ],
  "In Guezzam": [
    { id: 5801, name: "المنيعة", nameAscii: "El Meniaa" },
    { id: 5802, name: "حاسي الفحل", nameAscii: "Hassi Fehal" },
    { id: 5803, name: "حاسي القارة", nameAscii: "Hassi Gara" },
  ],
};
