import uuid
from app.db.session import SessionLocal
from app.models.supplier import Supplier

db = SessionLocal()
store_id = '7cdfc527-ea35-4bdb-acd3-d6f8646b6d47'

suppliers_data = [
    {
        "name": "Global Travel Goods SARL",
        "code": "SUP-GTG-001",
        "phone": "+213555123456",
        "email": "contact@globaltravelgoods.dz",
        "address": "Zone Industrielle Oued Smar, Lot 14",
        "city": "Alger",
        "tax_id": "001923847563829",
        "total_due": 45000000,
        "total_paid": 30000000,
        "total_remaining": 15000000,
        "reliability_score": 98.5,
        "note": "Fournisseur principal pour les coussins à mémoire de forme et les masques de sommeil. Très fiable, respecte toujours les délais de livraison.",
        "payment_terms_days": 30,
        "lead_time_days": 5,
        "min_order_qty": 100,
        "min_order_amount": 500000,
        "credit_limit": 20000000,
        "discount_rate": 5.0,
        "currency": "DZD",
        "delivery_method": "Camion frigorifique / standard",
        "return_policy": "Retours acceptés sous 15 jours si défaut de fabrication. Remboursement sous forme d'avoir.",
        "bank_account": "BEA 002 00012 34567890 11",
        "supply_category": "Confort & Sommeil",
        "fees": [{"label": "Frais de déchargement", "amount": 2500, "fee_type": "fixed", "is_recurring": False}],
        "custom_fields": {"directeur_commercial": "Mr. Karim Yelles", "notation_qualite": "A+", "langues_parlees": "Arabe, Français, Anglais"},
        "is_verified": True
    },
    {
        "name": "Accessoires Voyage Pro EURL",
        "code": "SUP-AVP-002",
        "phone": "+213661987654",
        "email": "commandes@avpro.dz",
        "address": "Rue des Frères Abdeslami, Kouba",
        "city": "Alger",
        "tax_id": "002019283746555",
        "total_due": 12000000,
        "total_paid": 12000000,
        "total_remaining": 0,
        "reliability_score": 95.0,
        "note": "Spécialiste de la bagagerie légère et organisateurs de valises. Attention : rupture de stock fréquente pendant l'été.",
        "payment_terms_days": 15,
        "lead_time_days": 7,
        "min_order_qty": 50,
        "min_order_amount": 200000,
        "credit_limit": 5000000,
        "discount_rate": 2.5,
        "currency": "DZD",
        "delivery_method": "Livraison par fourgon",
        "return_policy": "Échange standard uniquement. Pas de retour pour invendus.",
        "bank_account": "CPA 004 00123 98765432 99",
        "supply_category": "Rangement & Bagagerie",
        "fees": [{"label": "Frais de livraison express", "amount": 1500, "fee_type": "variable", "is_recurring": False}],
        "custom_fields": {"contact_logistique": "Mme. Samia", "type_emballage": "Carton renforcé"},
        "is_verified": True
    },
    {
        "name": "Tech & Connect Voyage Import",
        "code": "SUP-TCV-003",
        "phone": "+213770112233",
        "email": "import@techconnectvoyage.com",
        "address": "Centre des Affaires, Bab Ezzouar",
        "city": "Alger",
        "tax_id": "001839485761223",
        "total_due": 85000000,
        "total_paid": 60000000,
        "total_remaining": 25000000,
        "reliability_score": 88.0,
        "note": "Fournisseur pour les adaptateurs universels, pèse-bagages électroniques et autres gadgets. Délais de dédouanement parfois longs.",
        "payment_terms_days": 45,
        "lead_time_days": 21,
        "min_order_qty": 200,
        "min_order_amount": 1500000,
        "credit_limit": 30000000,
        "discount_rate": 8.0,
        "currency": "DZD",
        "delivery_method": "Fret maritime + Transport routier",
        "return_policy": "Garantie 1 an sur l'électronique. Remplacement direct des pièces défectueuses.",
        "bank_account": "BNA 001 00555 12345678 44",
        "supply_category": "Électronique & Gadgets",
        "fees": [{"label": "Frais de douane forfaitaire", "amount": 15000, "fee_type": "fixed", "is_recurring": True}],
        "custom_fields": {"agent_transitaire": "FastTransit DZ", "certifications": "CE, RoHS, FCC"},
        "is_verified": False
    },
    {
        "name": "Confort Textile Oran",
        "code": "SUP-CTO-004",
        "phone": "+21341334455",
        "email": "ventes@confort-textile-oran.dz",
        "address": "Zone d'Activité Es Senia",
        "city": "Oran",
        "tax_id": "001748392019485",
        "total_due": 22000000,
        "total_paid": 15000000,
        "total_remaining": 7000000,
        "reliability_score": 99.0,
        "note": "Excellente qualité pour les couvertures polaires et les serviettes en microfibre. Production locale, réactivité exceptionnelle.",
        "payment_terms_days": 0,  # Cash on delivery
        "lead_time_days": 3,
        "min_order_qty": 30,
        "min_order_amount": 100000,
        "credit_limit": 10000000,
        "discount_rate": 0.0,
        "currency": "DZD",
        "delivery_method": "Yalidine Express / Agence à Agence",
        "return_policy": "Retours non acceptés sauf erreur de coloris de leur part.",
        "bank_account": "SGA 021 00444 88877766 22",
        "supply_category": "Textile & Linge",
        "fees": [],
        "custom_fields": {"production": "100% Locale (Made in Blad)", "capacité_mensuelle": "5000 pièces"},
        "is_verified": True
    },
    {
        "name": "Safety & Anti-Theft Gear",
        "code": "SUP-STG-005",
        "phone": "+213550998877",
        "email": "b2b@safetygear.dz",
        "address": "Cité 11 Décembre, Dely Ibrahim",
        "city": "Alger",
        "tax_id": "002138475629103",
        "total_due": 35000000,
        "total_paid": 34000000,
        "total_remaining": 1000000,
        "reliability_score": 92.5,
        "note": "Fournit les sacs à dos antivol imperméables. Les prix sont un peu élevés mais la qualité justifie le prix. Bon service après-vente.",
        "payment_terms_days": 30,
        "lead_time_days": 10,
        "min_order_qty": 20,
        "min_order_amount": 300000,
        "credit_limit": 15000000,
        "discount_rate": 3.0,
        "currency": "DZD",
        "delivery_method": "Transporteur privé",
        "return_policy": "Retours acceptés sous 30 jours. Frais de retour à notre charge si défaut.",
        "bank_account": "BNP 027 00333 44455566 88",
        "supply_category": "Bagagerie Premium",
        "fees": [{"label": "Assurance transport", "amount": 5000, "fee_type": "variable", "is_recurring": False}],
        "custom_fields": {"manager_compte": "Amine", "materiaux_utilises": "Nylon Balistique 1680D"},
        "is_verified": True
    }
]

added = 0
for s_data in suppliers_data:
    existing = db.query(Supplier).filter_by(store_id=store_id, code=s_data["code"]).first()
    if existing:
        continue
    
    supplier = Supplier(
        id=str(uuid.uuid4()),
        store_id=store_id,
        name=s_data["name"],
        code=s_data["code"],
        phone=s_data["phone"],
        email=s_data["email"],
        address=s_data["address"],
        city=s_data["city"],
        tax_id=s_data["tax_id"],
        total_due=s_data["total_due"],
        total_paid=s_data["total_paid"],
        total_remaining=s_data["total_remaining"],
        reliability_score=s_data["reliability_score"],
        note=s_data["note"],
        payment_terms_days=s_data["payment_terms_days"],
        lead_time_days=s_data["lead_time_days"],
        min_order_qty=s_data["min_order_qty"],
        min_order_amount=s_data["min_order_amount"],
        credit_limit=s_data["credit_limit"],
        discount_rate=s_data["discount_rate"],
        currency=s_data["currency"],
        delivery_method=s_data["delivery_method"],
        return_policy=s_data["return_policy"],
        bank_account=s_data["bank_account"],
        supply_category=s_data["supply_category"],
        fees=s_data["fees"],
        custom_fields=s_data["custom_fields"],
        is_verified=s_data["is_verified"]
    )
    db.add(supplier)
    added += 1

db.commit()
print(f"Added {added} detailed suppliers!")
