from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session, joinedload
from typing import Optional, Any
from datetime import datetime, timezone, timedelta
import calendar
import uuid
import logging

logger = logging.getLogger(__name__)

from app.api import deps
from app.models.user import User
from app.models.payroll import PayrollRecord
from app.services.salary_service import compute_salary

router = APIRouter()

PAYABLE_ROLES = ["CONFIRMATEUR", "AGENT", "AGENT_MANAGER", "MANAGER", "MARKETER"]


def _require_super_admin(current_user: User):
    if current_user.role not in ("SUPER_ADMIN", "ADMIN"):
        raise HTTPException(status_code=403, detail="Réservé au super-admin.")


def _previous_period() -> str:
    today = datetime.now(timezone.utc)
    first = today.replace(day=1)
    prev = first - timedelta(days=1)
    return prev.strftime("%Y-%m")


def _period_bounds(period: str):
    try:
        year, month = int(period[:4]), int(period[5:7])
        start = datetime(year, month, 1)
        last_day = calendar.monthrange(year, month)[1]
        end = datetime(year, month, last_day, 23, 59, 59, 999999)
        return start, end
    except (ValueError, IndexError):
        raise HTTPException(status_code=400, detail="Période invalide — format attendu : YYYY-MM.")


def _record_out(r: PayrollRecord) -> dict:
    return {
        "id": r.id,
        "user_id": r.user_id,
        "user_name": r.user.name if r.user else None,
        "user_role": r.user.role if r.user else None,
        "period": r.period,
        "payment_type": r.payment_type,
        "base_salary": r.base_salary,
        "bonus": r.bonus,
        "total": r.total,
        "delivered_count": r.delivered_count,
        "recovered_count": r.recovered_count,
        "status": r.status,
        "generated_at": r.generated_at.isoformat() if r.generated_at else None,
        "paid_at": r.paid_at.isoformat() if r.paid_at else None,
    }


@router.post("/generate", response_model=dict)
def generate_payroll(
    period: Optional[str] = Query(None, description="YYYY-MM (défaut : mois précédent)"),
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_active_user),
) -> Any:
    """
    Freeze the monthly payroll: computes the salary of every active payable
    employee for the period and stores an immutable PayrollRecord.
    Re-running refreshes PENDING records; PAID records are never touched.
    """
    _require_super_admin(current_user)
    period = period or _previous_period()
    since, until = _period_bounds(period)

    employees = db.query(User).filter(
        User.role.in_(PAYABLE_ROLES),
        User.is_active == True,
    ).all()

    created, updated, skipped_paid = 0, 0, 0
    for emp in employees:
        salary = compute_salary(db, emp, store_id=None, since=since, until=until)

        record = db.query(PayrollRecord).filter(
            PayrollRecord.user_id == emp.id,
            PayrollRecord.period == period,
        ).first()

        if record and record.status == "PAID":
            skipped_paid += 1
            continue

        if not record:
            record = PayrollRecord(id=str(uuid.uuid4()), user_id=emp.id, period=period)
            db.add(record)
            created += 1
        else:
            updated += 1

        record.payment_type = salary.get("payment_type")
        record.base_salary = float(salary.get("base_salary") or 0)
        record.bonus = float(salary.get("abandoned_bonus") or 0)
        record.total = float(salary.get("salary") or 0)
        record.delivered_count = int(salary.get("normal_delivered_count") or 0)
        record.recovered_count = int(salary.get("recovered_delivered_count") or 0)
        record.breakdown = salary
        record.generated_by = current_user.id

    db.commit()
    logger.info("Payroll %s generated by %s: %d created, %d refreshed, %d already paid",
                period, current_user.id, created, updated, skipped_paid)
    return {
        "success": True,
        "period": period,
        "created": created,
        "updated": updated,
        "skipped_paid": skipped_paid,
        "message": f"Paie {period} : {created} fiche(s) créée(s), {updated} actualisée(s), {skipped_paid} déjà payée(s).",
    }


@router.get("/", response_model=dict)
def list_payroll(
    period: Optional[str] = Query(None, description="YYYY-MM (défaut : mois précédent)"),
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_active_user),
) -> Any:
    _require_super_admin(current_user)
    period = period or _previous_period()

    records = (
        db.query(PayrollRecord)
        .options(joinedload(PayrollRecord.user))
        .filter(PayrollRecord.period == period)
        .order_by(PayrollRecord.total.desc())
        .all()
    )
    total_pending = sum(r.total for r in records if r.status == "PENDING")
    total_paid = sum(r.total for r in records if r.status == "PAID")
    return {
        "success": True,
        "period": period,
        "data": [_record_out(r) for r in records],
        "summary": {
            "count": len(records),
            "pending_count": sum(1 for r in records if r.status == "PENDING"),
            "paid_count": sum(1 for r in records if r.status == "PAID"),
            "total_pending": total_pending,
            "total_paid": total_paid,
            "total": total_pending + total_paid,
        },
    }


@router.post("/{record_id}/mark-paid", response_model=dict)
def mark_paid(
    record_id: str,
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_active_user),
) -> Any:
    _require_super_admin(current_user)
    record = db.query(PayrollRecord).filter(PayrollRecord.id == record_id).first()
    if not record:
        raise HTTPException(status_code=404, detail="Fiche de paie introuvable.")
    if record.status == "PAID":
        return {"success": True, "message": "Déjà marquée payée."}

    record.status = "PAID"
    record.paid_at = datetime.now(timezone.utc).replace(tzinfo=None)
    record.paid_by = current_user.id
    db.commit()
    logger.info("Payroll record %s (period %s) marked PAID by %s", record.id, record.period, current_user.id)
    return {"success": True, "message": "Fiche marquée payée."}


@router.get("/reminders", response_model=dict)
def payroll_reminders(
    db: Session = Depends(deps.get_db),
    current_user: User = Depends(deps.get_current_active_user),
) -> Any:
    """
    Monthly payroll reminders for the super-admin:
    - previous month not generated at all → GENERATE reminder
    - generated but some records still PENDING → PAY reminder
    """
    if current_user.role not in ("SUPER_ADMIN", "ADMIN"):
        return {"success": True, "reminders": []}

    period = _previous_period()
    records = db.query(PayrollRecord).filter(PayrollRecord.period == period).all()

    reminders = []
    if not records:
        payable = db.query(User).filter(User.role.in_(PAYABLE_ROLES), User.is_active == True).count()
        if payable > 0:
            reminders.append({
                "type": "GENERATE",
                "period": period,
                "message": f"La paie de {period} n'a pas encore été générée ({payable} employé(s) à payer).",
            })
    else:
        pending = [r for r in records if r.status == "PENDING"]
        if pending:
            reminders.append({
                "type": "PAY",
                "period": period,
                "pending_count": len(pending),
                "total_pending": sum(r.total for r in pending),
                "message": f"Paie {period} : {len(pending)} fiche(s) en attente de paiement "
                           f"({sum(r.total for r in pending):,.0f} DA au total).",
            })

    return {"success": True, "period": period, "reminders": reminders}
