"""Update expenses table

Revision ID: b71e6466de2a
Revises: eaf8d5e0f891
Create Date: 2026-06-01 14:50:50.205704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b71e6466de2a'
down_revision: Union[str, Sequence[str], None] = 'eaf8d5e0f891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('noest_tracking_events_order_id_event_key_key'), table_name='noest_tracking_events')
    op.drop_index(op.f('noest_tracking_events_order_id_idx'), table_name='noest_tracking_events')
    op.drop_index(op.f('noest_tracking_events_tracking_number_idx'), table_name='noest_tracking_events')
    op.drop_table('noest_tracking_events')
    op.alter_column('delivery_fee_grids', 'home_fee',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('delivery_fee_grids', 'office_fee',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('delivery_fee_grids_partner_id_wilaya_id_key'), table_name='delivery_fee_grids')
    op.drop_constraint(op.f('delivery_fee_grids_partner_id_fkey'), 'delivery_fee_grids', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_fee_grids', 'delivery_partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('delivery_partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('delivery_partners_store_id_code_key'), table_name='delivery_partners')
    op.drop_index(op.f('delivery_partners_store_id_idx'), table_name='delivery_partners')
    op.create_index(op.f('ix_delivery_partners_store_id'), 'delivery_partners', ['store_id'], unique=False)
    op.drop_constraint(op.f('delivery_partners_store_id_fkey'), 'delivery_partners', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_partners', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_column('delivery_partners', 'is_api_enabled')
    op.drop_column('delivery_partners', 'api_config')
    op.add_column('expenses', sa.Column('term_type', sa.String(), nullable=True))
    op.alter_column('order_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               nullable=True)
    op.create_index(op.f('ix_order_events_created_at'), 'order_events', ['created_at'], unique=False)
    op.create_foreign_key(None, 'order_events', 'users', ['actor_id'], ['id'])
    op.drop_column('order_events', 'scheduled_at')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('orders_carrier_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'delivery_partners', ['carrier_id'], ['id'])
    op.drop_constraint(op.f('pos_sale_items_product_id_fkey'), 'pos_sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'pos_sale_items', 'products', ['product_id'], ['id'])
    op.alter_column('product_delivery_partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_delivery_partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('product_delivery_partners_product_id_fkey'), 'product_delivery_partners', type_='foreignkey')
    op.drop_constraint(op.f('product_delivery_partners_partner_id_fkey'), 'product_delivery_partners', type_='foreignkey')
    op.create_foreign_key(None, 'product_delivery_partners', 'delivery_partners', ['partner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_delivery_partners', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'pack_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'pack_charges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'pack_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'allowed_carriers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('uq_store_product_slug'), table_name='products')
    op.create_unique_constraint('uq_store_product_slug', 'products', ['store_id', 'slug'])
    op.drop_constraint(op.f('purchase_items_product_id_fkey'), 'purchase_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_items', 'products', ['product_id'], ['id'])
    op.alter_column('purchases', 'photos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(op.f('purchases_validated_by_fkey'), 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'users', ['validated_by'], ['id'])
    op.drop_constraint(op.f('return_items_product_id_fkey'), 'return_items', type_='foreignkey')
    op.create_foreign_key(None, 'return_items', 'products', ['product_id'], ['id'])
    op.alter_column('reviews', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stock_movements', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(precision=6),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('stock_movements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.drop_constraint(op.f('stock_movements_product_id_fkey'), 'stock_movements', type_='foreignkey')
    op.create_foreign_key(None, 'stock_movements', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('store_visitors', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('store_visitors', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('store_visitors', 'visited_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_store_visitors_id'), 'store_visitors', ['id'], unique=False)
    op.drop_constraint(op.f('store_visitors_store_id_fkey'), 'store_visitors', type_='foreignkey')
    op.create_foreign_key(None, 'store_visitors', 'stores', ['store_id'], ['id'])
    op.alter_column('stores', 'marketing_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('suppliers', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('suppliers', 'extra_charges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'assigned_store_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'assigned_product_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'assigned_product_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('users', 'assigned_store_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('suppliers', 'extra_charges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('suppliers', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('stores', 'marketing_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'store_visitors', type_='foreignkey')
    op.create_foreign_key(op.f('store_visitors_store_id_fkey'), 'store_visitors', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_store_visitors_id'), table_name='store_visitors')
    op.alter_column('store_visitors', 'visited_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('store_visitors', 'updated_at')
    op.drop_column('store_visitors', 'created_at')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key(op.f('stock_movements_product_id_fkey'), 'stock_movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.alter_column('stock_movements', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=6),
               nullable=False)
    op.alter_column('stock_movements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=6),
               existing_nullable=False)
    op.alter_column('stock_movements', 'expiration_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(precision=6),
               existing_nullable=True)
    op.alter_column('reviews', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'return_items', type_='foreignkey')
    op.create_foreign_key(op.f('return_items_product_id_fkey'), 'return_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_validated_by_fkey'), 'purchases', 'users', ['validated_by'], ['id'], ondelete='SET NULL')
    op.alter_column('purchases', 'photos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_items_product_id_fkey'), 'purchase_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_store_product_slug', 'products', type_='unique')
    op.create_index(op.f('uq_store_product_slug'), 'products', ['store_id', 'slug'], unique=True)
    op.alter_column('products', 'allowed_carriers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'pack_options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'pack_charges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('products', 'pack_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_constraint(None, 'product_delivery_partners', type_='foreignkey')
    op.drop_constraint(None, 'product_delivery_partners', type_='foreignkey')
    op.create_foreign_key(op.f('product_delivery_partners_partner_id_fkey'), 'product_delivery_partners', 'delivery_partners', ['partner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('product_delivery_partners_product_id_fkey'), 'product_delivery_partners', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('product_delivery_partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_delivery_partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'pos_sale_items', type_='foreignkey')
    op.create_foreign_key(op.f('pos_sale_items_product_id_fkey'), 'pos_sale_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_carrier_id_fkey'), 'orders', 'delivery_partners', ['carrier_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('order_events', sa.Column('scheduled_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_events', type_='foreignkey')
    op.drop_index(op.f('ix_order_events_created_at'), table_name='order_events')
    op.alter_column('order_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=6),
               nullable=False)
    op.drop_column('expenses', 'term_type')
    op.add_column('delivery_partners', sa.Column('api_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('delivery_partners', sa.Column('is_api_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'delivery_partners', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_partners_store_id_fkey'), 'delivery_partners', 'stores', ['store_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_delivery_partners_store_id'), table_name='delivery_partners')
    op.create_index(op.f('delivery_partners_store_id_idx'), 'delivery_partners', ['store_id'], unique=False)
    op.create_index(op.f('delivery_partners_store_id_code_key'), 'delivery_partners', ['store_id', 'code'], unique=True)
    op.alter_column('delivery_partners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'delivery_fee_grids', type_='foreignkey')
    op.create_foreign_key(op.f('delivery_fee_grids_partner_id_fkey'), 'delivery_fee_grids', 'delivery_partners', ['partner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('delivery_fee_grids_partner_id_wilaya_id_key'), 'delivery_fee_grids', ['partner_id', 'wilaya_id'], unique=True)
    op.alter_column('delivery_fee_grids', 'office_fee',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('delivery_fee_grids', 'home_fee',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('noest_tracking_events',
    sa.Column('id', sa.TEXT(), server_default=sa.text('(gen_random_uuid())::text'), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('causer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('noest_tracking_events_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('noest_tracking_events_pkey'))
    )
    op.create_index(op.f('noest_tracking_events_tracking_number_idx'), 'noest_tracking_events', ['tracking_number'], unique=False)
    op.create_index(op.f('noest_tracking_events_order_id_idx'), 'noest_tracking_events', ['order_id'], unique=False)
    op.create_index(op.f('noest_tracking_events_order_id_event_key_key'), 'noest_tracking_events', ['order_id', 'event_key'], unique=True)
    # ### end Alembic commands ###
