"""add_composite_indexes

Revision ID: f5b290e70af1
Revises: b71e6466de2a
Create Date: 2026-06-13 13:59:32.323446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b290e70af1'
down_revision: Union[str, Sequence[str], None] = 'b71e6466de2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_customer_store_blacklist', 'customers', ['store_id', 'is_blacklisted'], unique=False)
    op.create_index('idx_customer_store_phone', 'customers', ['store_id', 'phone'], unique=False)
    op.create_index('idx_expense_store_category', 'expenses', ['store_id', 'category'], unique=False)
    op.create_index('idx_expense_store_date', 'expenses', ['store_id', 'expense_date'], unique=False)
    op.create_index('idx_finance_store_date', 'financial_transactions', ['store_id', 'transaction_date'], unique=False)
    op.create_index('idx_order_store_created', 'orders', ['store_id', 'created_at'], unique=False)
    op.create_index('idx_order_store_deleted', 'orders', ['store_id', 'is_deleted'], unique=False)
    op.create_index('idx_order_store_status', 'orders', ['store_id', 'status'], unique=False)
    op.create_index('idx_product_store_active', 'products', ['store_id', 'is_active'], unique=False)
    op.create_index('idx_product_store_category', 'products', ['store_id', 'category'], unique=False)
    op.create_index('idx_stock_prod_created', 'stock_movements', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_prod_created', table_name='stock_movements')
    op.drop_index('idx_product_store_category', table_name='products')
    op.drop_index('idx_product_store_active', table_name='products')
    op.drop_index('idx_order_store_status', table_name='orders')
    op.drop_index('idx_order_store_deleted', table_name='orders')
    op.drop_index('idx_order_store_created', table_name='orders')
    op.drop_index('idx_finance_store_date', table_name='financial_transactions')
    op.drop_index('idx_expense_store_date', table_name='expenses')
    op.drop_index('idx_expense_store_category', table_name='expenses')
    op.drop_index('idx_customer_store_phone', table_name='customers')
    op.drop_index('idx_customer_store_blacklist', table_name='customers')
    # ### end Alembic commands ###
